export interface KanjiPrimitive {
    id: number;
    symbols: string[];
    label: string;
    meaning: string;
    sourcePage: number;
    dbMatches: string[];
}

const primitiveRows: Array<Omit<KanjiPrimitive, 'id' | 'label'>> = [
    { symbols: ["目"], meaning: "eye", sourcePage: 20, dbMatches: ["目"] },
    { symbols: ["丨"], meaning: "walking stick", sourcePage: 27, dbMatches: [] },
    { symbols: ["丶"], meaning: "Drop of", sourcePage: 27, dbMatches: [] },
    { symbols: ["尃"], meaning: "acupuncturist", sourcePage: 31, dbMatches: [] },
    { symbols: ["卜"], meaning: "divining rod", sourcePage: 32, dbMatches: [] },
    { symbols: ["卓"], meaning: "table", sourcePage: 34, dbMatches: ["卓"] },
    { symbols: ["八"], meaning: "eight", sourcePage: 35, dbMatches: ["八"] },
    { symbols: ["儿"], meaning: "human legs", sourcePage: 35, dbMatches: [] },
    { symbols: ["几"], meaning: "wind/weather vain", sourcePage: 36, dbMatches: [] },
    { symbols: ["勹"], meaning: "bound up", sourcePage: 36, dbMatches: [] },
    { symbols: ["𠂊"], meaning: "bound up small", sourcePage: 36, dbMatches: [] },
    { symbols: ["丷"], meaning: "horns", sourcePage: 36, dbMatches: [] },
    { symbols: ["亅"], meaning: "straightened hook", sourcePage: 44, dbMatches: [] },
    { symbols: ["乙"], meaning: "latter", sourcePage: 44, dbMatches: ["乙"] },
    { symbols: ["𠂇"], meaning: "By ones side", sourcePage: 46, dbMatches: [] },
    { symbols: ["刂"], meaning: "saber", sourcePage: 48, dbMatches: [] },
    { symbols: ["冨"], meaning: "wealth", sourcePage: 50, dbMatches: [] },
    { symbols: ["毋"], meaning: "mama", sourcePage: 54, dbMatches: [] },
    { symbols: ["小"], meaning: "small", sourcePage: 57, dbMatches: ["小"] },
    { symbols: ["厂"], meaning: "cliff", sourcePage: 59, dbMatches: [] },
    { symbols: ["巛"], meaning: "river alt 1", sourcePage: 64, dbMatches: [] },
    { symbols: ["巜"], meaning: "river alt 2", sourcePage: 64, dbMatches: [] },
    { symbols: ["水", "氵"], meaning: "water", sourcePage: 65, dbMatches: ["水"] },
    { symbols: ["泉"], meaning: "fountain", sourcePage: 66, dbMatches: ["泉"] },
    { symbols: ["灬"], meaning: "fire alt", sourcePage: 76, dbMatches: [] },
    { symbols: ["冂"], meaning: "hood", sourcePage: 83, dbMatches: [] },
    { symbols: ["宀"], meaning: "house", sourcePage: 85, dbMatches: [] },
    { symbols: ["干"], meaning: "left to dry", sourcePage: 88, dbMatches: ["干"] },
    { symbols: ["艹"], meaning: "flower", sourcePage: 97, dbMatches: [] },
    { symbols: ["莫"], meaning: "graveyard", sourcePage: 99, dbMatches: [] },
    { symbols: ["亀"], meaning: "turtle", sourcePage: 104, dbMatches: ["亀"] },
    { symbols: ["犭"], meaning: "pack of dogs", sourcePage: 105, dbMatches: [] },
    { symbols: ["牛"], meaning: "cow", sourcePage: 107, dbMatches: ["牛"] },
    { symbols: ["𠆢"], meaning: "umbrella", sourcePage: 109, dbMatches: [] },
    { symbols: ["亼"], meaning: "meeting", sourcePage: 110, dbMatches: [] },
    { symbols: ["⻌"], meaning: "road", sourcePage: 122, dbMatches: [] },
    { symbols: ["夂"], meaning: "walking legs", sourcePage: 125, dbMatches: [] },
    { symbols: ["軍"], meaning: "army", sourcePage: 125, dbMatches: ["軍"] },
    { symbols: ["冖"], meaning: "crown", sourcePage: 128, dbMatches: [] },
    { symbols: ["亠"], meaning: "top hat", sourcePage: 130, dbMatches: [] },
    { symbols: ["亢"], meaning: "whirlwind", sourcePage: 130, dbMatches: [] },
    { symbols: ["高"], meaning: "high", sourcePage: 131, dbMatches: ["高"] },
    { symbols: ["吉"], meaning: "good luck", sourcePage: 133, dbMatches: ["吉"] },
    { symbols: ["聿"], meaning: "brush", sourcePage: 136, dbMatches: [] },
    { symbols: ["⺻"], meaning: "brush alt", sourcePage: 136, dbMatches: [] },
    { symbols: ["攵"], meaning: "taskmaster", sourcePage: 137, dbMatches: [] },
    { symbols: ["矢"], meaning: "arrow", sourcePage: 143, dbMatches: ["矢"] },
    { symbols: ["弋"], meaning: "quiver", sourcePage: 144, dbMatches: [] },
    { symbols: ["戈"], meaning: "fiesta", sourcePage: 144, dbMatches: [] },
    { symbols: ["戊"], meaning: "parade", sourcePage: 145, dbMatches: [] },
    { symbols: ["戔"], meaning: "thanksgiving", sourcePage: 145, dbMatches: [] },
    { symbols: ["戌"], meaning: "march", sourcePage: 147, dbMatches: [] },
    { symbols: ["戍"], meaning: "float", sourcePage: 148, dbMatches: [] },
    { symbols: ["疋"], meaning: "mending", sourcePage: 152, dbMatches: [] },
    { symbols: ["廴"], meaning: "stretch", sourcePage: 154, dbMatches: [] },
    { symbols: ["豸"], meaning: "zoo", sourcePage: 155, dbMatches: [] },
    { symbols: ["豸"], meaning: "zoo alt", sourcePage: 155, dbMatches: [] },
    { symbols: ["巾"], meaning: "piece of fabric", sourcePage: 156, dbMatches: ["巾"] },
    { symbols: ["衣"], meaning: "garment", sourcePage: 156, dbMatches: ["衣"] },
    { symbols: ["衤"], meaning: "top hat and scarf", sourcePage: 156, dbMatches: [] },
    { symbols: ["巿"], meaning: "apron", sourcePage: 160, dbMatches: [] },
    { symbols: ["帀"], meaning: "belt", sourcePage: 161, dbMatches: [] },
    { symbols: ["巴"], meaning: "buckle", sourcePage: 161, dbMatches: [] },
    { symbols: ["云"], meaning: "rising cloud", sourcePage: 162, dbMatches: [] },
    { symbols: ["雨"], meaning: "rain", sourcePage: 163, dbMatches: ["雨"] },
    { symbols: ["冫"], meaning: "ice", sourcePage: 164, dbMatches: [] },
    { symbols: ["氷"], meaning: "ice", sourcePage: 164, dbMatches: ["氷"] },
    { symbols: ["巫"], meaning: "witch", sourcePage: 164, dbMatches: [] },
    { symbols: ["天"], meaning: "heaven", sourcePage: 165, dbMatches: ["天"] },
    { symbols: ["古"], meaning: "old", sourcePage: 167, dbMatches: ["古"] },
    { symbols: ["昜"], meaning: "siesta", sourcePage: 171, dbMatches: [] },
    { symbols: ["𠂆"], meaning: "reclining", sourcePage: 173, dbMatches: [] },
    { symbols: ["复"], meaning: "Double back", sourcePage: 175, dbMatches: [] },
    { symbols: ["音"], meaning: "sound", sourcePage: 178, dbMatches: ["音"] },
    { symbols: ["戠"], meaning: "kazoo", sourcePage: 179, dbMatches: [] },
    { symbols: ["竟"], meaning: "mirror", sourcePage: 180, dbMatches: [] },
    { symbols: ["鬼"], meaning: "oni", sourcePage: 183, dbMatches: ["鬼"] },
    { symbols: ["壬"], meaning: "porter", sourcePage: 185, dbMatches: [] },
    { symbols: ["也"], meaning: "scorpion", sourcePage: 191, dbMatches: [] },
    { symbols: ["䖵"], meaning: "gnats", sourcePage: 193, dbMatches: [] },
    { symbols: ["魚"], meaning: "fish", sourcePage: 195, dbMatches: ["魚"] },
    { symbols: ["豕"], meaning: "sow", sourcePage: 196, dbMatches: [] },
    { symbols: ["勿"], meaning: "must not", sourcePage: 197, dbMatches: ["勿"] },
    { symbols: ["易"], meaning: "easy", sourcePage: 197, dbMatches: ["易"] },
    { symbols: ["羊"], meaning: "sheep", sourcePage: 198, dbMatches: ["羊"] },
    { symbols: ["⺷"], meaning: "wool", sourcePage: 199, dbMatches: [] },
    { symbols: ["隹"], meaning: "turkey", sourcePage: 200, dbMatches: [] },
    { symbols: ["馬"], meaning: "horse", sourcePage: 203, dbMatches: ["馬"] },
    { symbols: ["羽"], meaning: "feathers", sourcePage: 204, dbMatches: ["羽"] },
    { symbols: ["囗"], meaning: "pent in", sourcePage: 206, dbMatches: [] },
    { symbols: ["穴"], meaning: "hole", sourcePage: 208, dbMatches: ["穴"] },
    { symbols: ["忄"], meaning: "state of mind", sourcePage: 209, dbMatches: [] },
    { symbols: ["心"], meaning: "heart", sourcePage: 209, dbMatches: ["心"] },
    { symbols: ["扌"], meaning: "finger", sourcePage: 216, dbMatches: [] },
    { symbols: ["廾"], meaning: "two hands", sourcePage: 219, dbMatches: [] },
    { symbols: ["才"], meaning: "talent", sourcePage: 221, dbMatches: ["才"] },
    { symbols: ["又"], meaning: "once again", sourcePage: 222, dbMatches: ["又"] },
    { symbols: ["殳"], meaning: "missile", sourcePage: 225, dbMatches: [] },
    { symbols: ["圣"], meaning: "spool", sourcePage: 226, dbMatches: [] },
    { symbols: ["隹"], meaning: "vulture", sourcePage: 227, dbMatches: [] },
    { symbols: ["鳥"], meaning: "bird", sourcePage: 228, dbMatches: ["鳥"] },
    { symbols: ["厶"], meaning: "elbow", sourcePage: 229, dbMatches: [] },
    { symbols: ["西"], meaning: "west", sourcePage: 229, dbMatches: ["西"] },
    { symbols: ["云"], meaning: "wall", sourcePage: 231, dbMatches: [] },
    { symbols: ["子"], meaning: "child", sourcePage: 232, dbMatches: ["子"] },
    { symbols: ["谷"], meaning: "valley", sourcePage: 237, dbMatches: ["谷"] },
    { symbols: ["尚"], meaning: "even more", sourcePage: 238, dbMatches: ["尚"] },
    { symbols: ["歹"], meaning: "bone", sourcePage: 240, dbMatches: [] },
    { symbols: ["目"], meaning: "eye", sourcePage: 241, dbMatches: ["目"] },
    { symbols: ["曼"], meaning: "mandala", sourcePage: 242, dbMatches: [] },
    { symbols: ["寺"], meaning: "Buddhist temple", sourcePage: 247, dbMatches: ["寺"] },
    { symbols: ["彳"], meaning: "going", sourcePage: 248, dbMatches: [] },
    { symbols: ["麦"], meaning: "wheat", sourcePage: 251, dbMatches: ["麦"] },
    { symbols: ["米"], meaning: "rice", sourcePage: 255, dbMatches: ["米"] },
    { symbols: ["人", "亻"], meaning: "person", sourcePage: 259, dbMatches: ["人"] },
    { symbols: ["从"], meaning: "assembly line", sourcePage: 268, dbMatches: [] },
    { symbols: ["耒"], meaning: "plow", sourcePage: 269, dbMatches: [] },
    { symbols: ["并"], meaning: "puzzle", sourcePage: 269, dbMatches: [] },
    { symbols: ["罒"], meaning: "sunglasses with one lens popped out", sourcePage: 271, dbMatches: [] },
    { symbols: ["㡀"], meaning: "shredder", sourcePage: 271, dbMatches: [] },
    { symbols: ["方"], meaning: "way", sourcePage: 272, dbMatches: ["方"] },
    { symbols: ["巾"], meaning: "piece of fabric", sourcePage: 273, dbMatches: ["巾"] },
    { symbols: ["㫃"], meaning: "flag", sourcePage: 274, dbMatches: [] },
    { symbols: ["礻", "示"], meaning: "demonstrate", sourcePage: 278, dbMatches: ["示"] },
    { symbols: ["乍"], meaning: "saw", sourcePage: 286, dbMatches: [] },
    { symbols: ["ヨ"], meaning: "broom", sourcePage: 287, dbMatches: [] },
    { symbols: ["彐"], meaning: "broom alt", sourcePage: 287, dbMatches: [] },
    { symbols: ["帚"], meaning: "broom old", sourcePage: 288, dbMatches: [] },
    { symbols: ["事"], meaning: "occurence", sourcePage: 289, dbMatches: ["事"] },
    { symbols: ["尹"], meaning: "mop", sourcePage: 289, dbMatches: [] },
    { symbols: ["柬"], meaning: "sieve", sourcePage: 289, dbMatches: [] },
    { symbols: ["而"], meaning: "comb", sourcePage: 290, dbMatches: [] },
    { symbols: ["凵"], meaning: "shovel", sourcePage: 291, dbMatches: [] },
    { symbols: ["皿"], meaning: "dish", sourcePage: 294, dbMatches: ["皿"] },
    { symbols: ["卉"], meaning: "haystack", sourcePage: 295, dbMatches: [] },
    { symbols: ["广"], meaning: "caverns", sourcePage: 295, dbMatches: [] },
    { symbols: ["夭"], meaning: "strawman", sourcePage: 296, dbMatches: [] },
    { symbols: ["癶"], meaning: "quarter", sourcePage: 297, dbMatches: [] },
    { symbols: ["矛"], meaning: "halberd", sourcePage: 301, dbMatches: ["矛"] },
    { symbols: ["弗"], meaning: "dollarsign", sourcePage: 302, dbMatches: [] },
    { symbols: ["弔"], meaning: "condolences", sourcePage: 302, dbMatches: ["弔"] },
    { symbols: ["亏"], meaning: "snare", sourcePage: 303, dbMatches: [] },
    { symbols: ["鳥"], meaning: "bird", sourcePage: 303, dbMatches: ["鳥"] },
    { symbols: ["与"], meaning: "bestow upon", sourcePage: 304, dbMatches: ["与"] },
    { symbols: ["老"], meaning: "elderly", sourcePage: 305, dbMatches: ["老"] },
    { symbols: ["夹"], meaning: "scissors", sourcePage: 307, dbMatches: [] },
    { symbols: ["白"], meaning: "white", sourcePage: 308, dbMatches: ["白"] },
    { symbols: ["骨"], meaning: "bone", sourcePage: 311, dbMatches: ["骨"] },
    { symbols: ["阝"], meaning: "pinnacle", sourcePage: 312, dbMatches: [] },
    { symbols: ["兀"], meaning: "miss universe/paper punch", sourcePage: 316, dbMatches: [] },
    { symbols: ["幺"], meaning: "cocoon", sourcePage: 322, dbMatches: [] },
    { symbols: ["卩"], meaning: "stamp", sourcePage: 325, dbMatches: [] },
    { symbols: ["卩"], meaning: "chop-seal", sourcePage: 325, dbMatches: [] },
    { symbols: ["㔾"], meaning: "chop-seal small", sourcePage: 326, dbMatches: [] },
    { symbols: ["巴"], meaning: "fingerprint", sourcePage: 328, dbMatches: [] },
    { symbols: ["阝"], meaning: "mailbox", sourcePage: 328, dbMatches: [] },
    { symbols: ["瓜"], meaning: "melon", sourcePage: 329, dbMatches: ["瓜"] },
    { symbols: ["冊"], meaning: "volume (of a book)", sourcePage: 329, dbMatches: ["冊"] },
    { symbols: ["壴"], meaning: "drum", sourcePage: 333, dbMatches: [] },
    { symbols: ["艮"], meaning: "silver alt", sourcePage: 334, dbMatches: [] },
    { symbols: ["艮"], meaning: "silver", sourcePage: 334, dbMatches: [] },
    { symbols: ["良"], meaning: "good", sourcePage: 336, dbMatches: ["良"] },
    { symbols: ["女"], meaning: "woman", sourcePage: 337, dbMatches: ["女"] },
    { symbols: ["乂"], meaning: "sheaf", sourcePage: 339, dbMatches: [] },
    { symbols: ["乜"], meaning: "earthworm", sourcePage: 340, dbMatches: [] },
    { symbols: ["辛"], meaning: "spicy", sourcePage: 341, dbMatches: ["辛"] },
    { symbols: ["辟"], meaning: "ketchup", sourcePage: 341, dbMatches: [] },
    { symbols: ["曲"], meaning: "curved", sourcePage: 342, dbMatches: ["曲"] },
    { symbols: ["先"], meaning: "before (timewise)", sourcePage: 343, dbMatches: ["先"] },
    { symbols: ["朮"], meaning: "resin", sourcePage: 345, dbMatches: [] },
    { symbols: ["韭"], meaning: "celery", sourcePage: 345, dbMatches: [] },
    { symbols: ["襄"], meaning: "grass skirt", sourcePage: 346, dbMatches: [] },
    { symbols: ["生"], meaning: "life", sourcePage: 347, dbMatches: ["生"] },
    { symbols: ["丰"], meaning: "bushes", sourcePage: 350, dbMatches: [] },
    { symbols: ["未"], meaning: "not yet", sourcePage: 351, dbMatches: ["未"] },
    { symbols: ["丰"], meaning: "cornstalk", sourcePage: 352, dbMatches: [] },
    { symbols: ["森"], meaning: "forest", sourcePage: 352, dbMatches: ["森"] },
    { symbols: ["奏"], meaning: "play music", sourcePage: 352, dbMatches: ["奏"] },
    { symbols: ["董"], meaning: "cabbage", sourcePage: 353, dbMatches: [] },
    { symbols: ["莫"], meaning: "scarecrow", sourcePage: 353, dbMatches: [] },
    { symbols: ["垂"], meaning: "droop", sourcePage: 354, dbMatches: ["垂"] },
    { symbols: ["西"], meaning: "west", sourcePage: 358, dbMatches: ["西"] },
    { symbols: ["ユ"], meaning: "key", sourcePage: 363, dbMatches: [] },
    { symbols: ["夫"], meaning: "husband", sourcePage: 363, dbMatches: ["夫"] },
    { symbols: ["革"], meaning: "leather", sourcePage: 364, dbMatches: ["革"] },
    { symbols: ["于"], meaning: "potato", sourcePage: 366, dbMatches: [] },
    { symbols: ["食"], meaning: "eat", sourcePage: 368, dbMatches: ["食"] },
    { symbols: ["疒"], meaning: "sickness", sourcePage: 370, dbMatches: [] },
    { symbols: ["匚"], meaning: "box", sourcePage: 371, dbMatches: [] },
    { symbols: ["凵"], meaning: "box small", sourcePage: 371, dbMatches: [] },
    { symbols: ["个"], meaning: "teepee", sourcePage: 373, dbMatches: [] },
    { symbols: ["𠆢"], meaning: "pop tent", sourcePage: 373, dbMatches: [] },
    { symbols: ["形"], meaning: "shape", sourcePage: 374, dbMatches: ["形"] },
    { symbols: ["并"], meaning: "fenceposts", sourcePage: 377, dbMatches: [] },
    { symbols: ["爻"], meaning: "sparkler", sourcePage: 378, dbMatches: [] },
    { symbols: ["果"], meaning: "fruit", sourcePage: 379, dbMatches: ["果"] },
    { symbols: ["巴"], meaning: "mosaic", sourcePage: 380, dbMatches: [] },
    { symbols: ["其"], meaning: "bushel basket", sourcePage: 382, dbMatches: [] },
    { symbols: ["串"], meaning: "skewer", sourcePage: 383, dbMatches: ["串"] },
    { symbols: ["且"], meaning: "there is more", sourcePage: 384, dbMatches: ["且"] },
    { symbols: ["桶"], meaning: "oaken tub", sourcePage: 384, dbMatches: [] },
    { symbols: ["行"], meaning: "go", sourcePage: 386, dbMatches: ["行"] },
    { symbols: ["甬"], meaning: "funnel", sourcePage: 390, dbMatches: [] },
    { symbols: ["冊"], meaning: "volume (of a book)", sourcePage: 391, dbMatches: ["冊"] },
    { symbols: ["氏"], meaning: "family name", sourcePage: 393, dbMatches: ["氏"] },
    { symbols: ["甫"], meaning: "dog tag", sourcePage: 393, dbMatches: [] },
    { symbols: ["阝"], meaning: "city walls", sourcePage: 394, dbMatches: [] },
    { symbols: ["曳"], meaning: "drag", sourcePage: 396, dbMatches: [] },
    { symbols: ["曵"], meaning: "drag alt", sourcePage: 396, dbMatches: [] },
    { symbols: ["𠃌"], meaning: "Clothes hanger", sourcePage: 397, dbMatches: [] },
    { symbols: ["主"], meaning: "(one's) master", sourcePage: 397, dbMatches: ["主"] },
    { symbols: ["毛"], meaning: "fur", sourcePage: 406, dbMatches: ["毛"] },
    { symbols: ["采"], meaning: "colorful dice", sourcePage: 406, dbMatches: ["采"] },
    { symbols: ["羽"], meaning: "feathers", sourcePage: 407, dbMatches: ["羽"] },
    { symbols: ["釆"], meaning: "hairpin", sourcePage: 408, dbMatches: [] },
    { symbols: ["髟"], meaning: "mane", sourcePage: 408, dbMatches: [] },
    { symbols: ["髪"], meaning: "hair", sourcePage: 408, dbMatches: ["髪"] },
    { symbols: ["梟"], meaning: "owl", sourcePage: 409, dbMatches: [] },
    { symbols: ["愛"], meaning: "love", sourcePage: 412, dbMatches: ["愛"] },
    { symbols: ["羌"], meaning: "mountain goat", sourcePage: 413, dbMatches: [] },
    { symbols: ["蛩"], meaning: "talking cricket", sourcePage: 413, dbMatches: [] },
    { symbols: ["岳"], meaning: "mountain peak", sourcePage: 414, dbMatches: ["岳"] },
    { symbols: ["豸"], meaning: "skunk", sourcePage: 416, dbMatches: [] },
    { symbols: ["虎"], meaning: "tiger", sourcePage: 419, dbMatches: ["虎"] },
    { symbols: ["鹿"], meaning: "deer", sourcePage: 421, dbMatches: ["鹿"] },
    { symbols: ["关"], meaning: "gold calf", sourcePage: 423, dbMatches: [] },
];

export const KANJI_PRIMITIVES: KanjiPrimitive[] = primitiveRows.map((row, index) => ({
    id: 900001 + index,
    label: row.symbols.join(' / '),
    ...row,
}));

export const KANJI_PRIMITIVE_IDS = KANJI_PRIMITIVES.map(primitive => primitive.id);

export function kanjiPrimitivesByIds(ids?: number[]): KanjiPrimitive[] {
    if (!ids || ids.length === 0) return KANJI_PRIMITIVES;
    const wanted = new Set(ids);
    return KANJI_PRIMITIVES.filter(primitive => wanted.has(primitive.id));
}
