INSERT INTO public.learning_decks (
  id, title, description, question_label, answer_label, question_format
) VALUES (
  'probability-chapter-3',
  'Probability · General Random Variables',
  'Learn continuous random variables, probability density functions, cumulative distribution functions, the normal law, conditioning on events, joint and conditional densities, the continuous Bayes rule and derived distributions.',
  'Question',
  'Answer',
  'multiple_choice'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  question_label = EXCLUDED.question_label,
  answer_label = EXCLUDED.answer_label,
  question_format = EXCLUDED.question_format;

INSERT INTO public.words10k (
  deck_id,
  source_id,
  source_page,
  section,
  step,
  step_title,
  japanese_word,
  english,
  authored_options,
  explanation
) VALUES
(
  'probability-chapter-3',
  'C3-N01',
  100,
  'section_4',
  'step_1',
  'Notation',
  'f_X(x)',
  'The probability density function of X',
  '["The probability density function of X","The probability that X equals x","The cumulative probability up to x","The mean of X"]'::jsonb,
  'A PDF is a density: only its area over a set is a probability.'
),
(
  'probability-chapter-3',
  'C3-N02',
  100,
  'section_4',
  'step_1',
  'Notation',
  '∫_B f_X(x) dx',
  'P(X ∈ B)',
  '["f_X(B)","P(X ∈ B)","The mean of X over B","The length of B"]'::jsonb,
  'Integrating the PDF over a set gives the probability of that set.'
),
(
  'probability-chapter-3',
  'C3-N03',
  109,
  'section_4',
  'step_1',
  'Notation',
  'F_X(x)',
  'P(X ≤ x)',
  '["P(X = x)","P(X ≥ x)","P(X ≤ x)","The density of X at x"]'::jsonb,
  'The CDF accumulates probability up to the value x.'
),
(
  'probability-chapter-3',
  'C3-N04',
  116,
  'section_4',
  'step_1',
  'Notation',
  'Φ(y)',
  'The CDF of the standard normal random variable',
  '["The PDF of the standard normal random variable","The mean of a normal random variable","The variance of a normal random variable","The CDF of the standard normal random variable"]'::jsonb,
  'Φ is reserved for the standard normal CDF, the function recorded in the normal table.'
),
(
  'probability-chapter-3',
  'C3-N05',
  114,
  'section_4',
  'step_1',
  'Notation',
  'μ in the normal PDF',
  'The mean of the random variable',
  '["The mean of the random variable","The standard deviation","The variance","The normalizing constant"]'::jsonb,
  'The normal PDF is symmetric around μ, which is therefore its mean.'
),
(
  'probability-chapter-3',
  'C3-N06',
  114,
  'section_4',
  'step_1',
  'Notation',
  'σ² in the normal PDF',
  'The variance of the random variable',
  '["The mean","The variance of the random variable","The standard deviation","The median"]'::jsonb,
  'σ is the standard deviation, so σ² is the variance.'
),
(
  'probability-chapter-3',
  'C3-N07',
  107,
  'section_4',
  'step_1',
  'Notation',
  'λ in the PDF λe^(−λx)',
  'The positive parameter of an exponential random variable',
  '["The mean of the random variable","The variance of the random variable","The positive parameter of an exponential random variable","A probability between 0 and 1"]'::jsonb,
  'The exponential parameter λ is positive; the mean is 1/λ, not λ.'
),
(
  'probability-chapter-3',
  'C3-N08',
  101,
  'section_4',
  'step_1',
  'Notation',
  'δ in P([x, x+δ]) ≈ f_X(x)·δ',
  'The length of a small interval',
  '["A probability","The density at x","The variance","The length of a small interval"]'::jsonb,
  'δ is an interval length taken small, which is why the approximation is good.'
),
(
  'probability-chapter-3',
  'C3-N09',
  124,
  'section_4',
  'step_1',
  'Notation',
  'f_{X,Y}(x,y)',
  'The joint PDF of X and Y',
  '["The joint PDF of X and Y","The conditional PDF of X given Y","The marginal PDF of X","The joint CDF of X and Y"]'::jsonb,
  'A joint PDF is integrated over a region of the plane to give a probability.'
),
(
  'probability-chapter-3',
  'C3-N10',
  128,
  'section_4',
  'step_1',
  'Notation',
  'f_{X|Y}(x | y)',
  'The conditional PDF of X given that Y = y',
  '["The joint PDF of X and Y","The conditional PDF of X given that Y = y","The marginal PDF of X","The probability that X = x given Y = y"]'::jsonb,
  'It is the joint PDF along the slice Y = y, renormalized to integrate to 1.'
),
(
  'probability-chapter-3',
  'C3-N11',
  118,
  'section_4',
  'step_1',
  'Notation',
  'f_{X|A}(x)',
  'The conditional PDF of X given the event A',
  '["The PDF of the event A","The probability of A given X = x","The conditional PDF of X given the event A","The joint PDF of X and A"]'::jsonb,
  'Conditioning on an event gives an ordinary PDF in a universe where A has occurred.'
),
(
  'probability-chapter-3',
  'C3-N12',
  121,
  'section_4',
  'step_1',
  'Notation',
  'E[X | A]',
  'The conditional expectation of X given the event A',
  '["The probability of A","The variance of X given A","The conditional PDF of X given A","The conditional expectation of X given the event A"]'::jsonb,
  'It integrates x against the conditional PDF f_{X|A}.'
),
(
  'probability-chapter-3',
  'C3-N13',
  105,
  'section_4',
  'step_1',
  'Notation',
  'var(X)',
  'The expected value of (X − E[X])²',
  '["The expected value of (X − E[X])²","The expected value of X − E[X]","The square root of the mean","The expected value of X²"]'::jsonb,
  'Variance is the expected squared distance from the mean.'
),
(
  'probability-chapter-3',
  'C3-N14',
  100,
  'section_4',
  'step_1',
  'Notation',
  'The dx in ∫ f_X(x) dx',
  'It names the variable the integration runs over',
  '["It is a small probability","It names the variable the integration runs over","It is the derivative of x","It is a constant multiplying the integral"]'::jsonb,
  'The differential marks which variable is being integrated, not a quantity of its own.'
),
(
  'probability-chapter-3',
  'C3-N15',
  143,
  'section_4',
  'step_1',
  'Notation',
  'h in "y = g(x) if and only if x = h(y)"',
  'The inverse of the function g',
  '["The derivative of g","The density of Y","The inverse of the function g","A second random variable"]'::jsonb,
  'A strictly monotonic g can be inverted, and h is that inverse.'
),
(
  'probability-chapter-3',
  'C3-N16',
  125,
  'section_4',
  'step_1',
  'Notation',
  '∫_{−∞}^{∞} f_{X,Y}(x,y) dy',
  'The marginal PDF f_X(x)',
  '["The joint CDF","The conditional PDF of X given Y","The normalization constant","The marginal PDF f_X(x)"]'::jsonb,
  'Integrating the joint PDF over the other variable leaves the marginal PDF.'
),
(
  'probability-chapter-3',
  'C3-01',
  100,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'What makes a random variable X continuous?',
  'Its probability law is described by a nonnegative function f_X whose integral over a set gives the probability of that set',
  '["Its probability law is described by a nonnegative function f_X whose integral over a set gives the probability of that set","It takes infinitely many values","Its CDF has jumps","Its PMF is uniform"]'::jsonb,
  'Continuity is defined by the existence of a PDF, not merely by having many values.'
),
(
  'probability-chapter-3',
  'C3-02',
  100,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'For a continuous random variable X and any single value a, P(X = a) equals',
  '0',
  '["f_X(a)","0","f_X(a)·a","1"]'::jsonb,
  'The integral of the PDF over a single point is zero, so including or excluding endpoints changes nothing.'
),
(
  'probability-chapter-3',
  'C3-03',
  100,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'Which condition must every PDF satisfy?',
  'f_X(x) ≥ 0 for all x and ∫_{−∞}^{∞} f_X(x) dx = 1',
  '["f_X(x) ≤ 1 for all x","f_X is increasing","f_X(x) ≥ 0 for all x and ∫_{−∞}^{∞} f_X(x) dx = 1","The sum of f_X over all x is 1"]'::jsonb,
  'A PDF must be nonnegative and enclose total area one; it is not bounded by one.'
),
(
  'probability-chapter-3',
  'C3-04',
  101,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'How should f_X(x) be interpreted?',
  'As probability mass per unit length near x',
  '["As the probability that X equals x","As the probability that X is at most x","As the average value of X near x","As probability mass per unit length near x"]'::jsonb,
  'For small δ, P([x, x+δ]) ≈ f_X(x)·δ, so f_X is a density per unit length.'
),
(
  'probability-chapter-3',
  'C3-05',
  104,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'Can a PDF take values larger than 1?',
  'Yes, provided the total area under it is still 1',
  '["Yes, provided the total area under it is still 1","No, a PDF is a probability","Only for discrete random variables","Only on intervals of length greater than 1"]'::jsonb,
  'The PDF of Example 3.3 grows without bound near zero and is still legitimate.'
),
(
  'probability-chapter-3',
  'C3-06',
  102,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'For a uniform random variable on [a,b], the constant value of the PDF is',
  '1/(b − a)',
  '["b − a","1/(b − a)","1/(b + a)","1/2"]'::jsonb,
  'The area of the rectangle of height c over [a,b] is c(b − a), which must equal one.'
),
(
  'probability-chapter-3',
  'C3-07',
  102,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'For X uniform on [a,b] and a set I, P(X ∈ I) equals',
  'length of [a,b] ∩ I divided by length of [a,b]',
  '["length of I divided by length of [a,b]","length of [a,b] ∩ I","length of [a,b] ∩ I divided by length of [a,b]","1/(b − a)"]'::jsonb,
  'Only the part of I inside [a,b] carries probability, measured as a fraction of the whole interval.'
),
(
  'probability-chapter-3',
  'C3-08',
  103,
  'section_4',
  'step_2',
  'Continuous random variables and PDFs',
  'For a piecewise constant PDF with values c_i on [a_i, a_{i+1}), normalization requires',
  'Σ c_i(a_{i+1} − a_i) = 1',
  '["Σ c_i = 1","Σ (a_{i+1} − a_i) = 1","max c_i = 1","Σ c_i(a_{i+1} − a_i) = 1"]'::jsonb,
  'Each piece contributes the area of its rectangle, and the areas must add to one.'
),
(
  'probability-chapter-3',
  'C3-09',
  104,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'The expected value of a continuous random variable X is defined as',
  '∫_{−∞}^{∞} x f_X(x) dx',
  '["∫_{−∞}^{∞} x f_X(x) dx","Σ_x x f_X(x)","∫_{−∞}^{∞} f_X(x) dx","the value x where f_X is largest"]'::jsonb,
  'The discrete sum is replaced by an integral of x against the density.'
),
(
  'probability-chapter-3',
  'C3-10',
  105,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'The expected value rule for Y = g(X) states that E[g(X)] equals',
  '∫_{−∞}^{∞} g(x) f_X(x) dx',
  '["g(E[X])","∫_{−∞}^{∞} g(x) f_X(x) dx","∫_{−∞}^{∞} g(x) dx","∫_{−∞}^{∞} x f_{g(X)}(x) dx"]'::jsonb,
  'The PDF of Y is not needed: integrate g against the PDF of X.'
),
(
  'probability-chapter-3',
  'C3-11',
  106,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'Which identity gives the variance from moments?',
  'var(X) = E[X²] − (E[X])²',
  '["var(X) = E[X]² − E[X²]","var(X) = E[X²] + (E[X])²","var(X) = E[X²] − (E[X])²","var(X) = E[(X − E[X])]"]'::jsonb,
  'Expanding (X − E[X])² and using linearity gives the second moment minus the squared mean.'
),
(
  'probability-chapter-3',
  'C3-12',
  106,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'For Y = aX + b with scalars a and b',
  'E[Y] = aE[X] + b and var(Y) = a²var(X)',
  '["E[Y] = aE[X] and var(Y) = a·var(X)","E[Y] = aE[X] + b and var(Y) = a²var(X) + b","E[Y] = E[X] + b and var(Y) = var(X)","E[Y] = aE[X] + b and var(Y) = a²var(X)"]'::jsonb,
  'Shifting moves the mean but not the spread; scaling multiplies the variance by a².'
),
(
  'probability-chapter-3',
  'C3-13',
  106,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'For X uniform on [a,b], the mean and variance are',
  '(a + b)/2 and (b − a)²/12',
  '["(a + b)/2 and (b − a)²/12","(a + b)/2 and (b − a)/12","(b − a)/2 and (b − a)²/12","(a + b)/2 and (b² − a²)/12"]'::jsonb,
  'Symmetry gives the midpoint as mean; the second moment (a² + ab + b²)/3 gives the variance.'
),
(
  'probability-chapter-3',
  'C3-14',
  107,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'The PDF of an exponential random variable with parameter λ is',
  'λe^(−λx) for x ≥ 0 and 0 otherwise',
  '["e^(−λx) for x ≥ 0 and 0 otherwise","λe^(−λx) for x ≥ 0 and 0 otherwise","λe^(−λx) for all x","(1/λ)e^(−x/λ) for all x"]'::jsonb,
  'The factor λ is what makes the area over [0, ∞) equal to one.'
),
(
  'probability-chapter-3',
  'C3-15',
  107,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'For an exponential random variable and any a ≥ 0, P(X ≥ a) equals',
  'e^(−λa)',
  '["1 − e^(−λa)","λe^(−λa)","e^(−λa)","e^(−a/λ)"]'::jsonb,
  'The tail probability falls exponentially, which is the integral of λe^(−λx) from a to infinity.'
),
(
  'probability-chapter-3',
  'C3-16',
  108,
  'section_4',
  'step_3',
  'Expectation and the exponential',
  'The mean and variance of an exponential random variable with parameter λ are',
  '1/λ and 1/λ²',
  '["λ and λ²","1/λ and 1/λ","1/λ² and 1/λ","1/λ and 1/λ²"]'::jsonb,
  'Integration by parts gives E[X] = 1/λ and E[X²] = 2/λ², leaving variance 1/λ².'
),
(
  'probability-chapter-3',
  'C3-17',
  109,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'Why is the CDF defined for every kind of random variable?',
  'Because {X ≤ x} is always an event and so always has a probability',
  '["Because {X ≤ x} is always an event and so always has a probability","Because every random variable has a PDF","Because every random variable has a PMF","Because every random variable is continuous"]'::jsonb,
  'The CDF needs only that {X ≤ x} be an event, which holds discrete or continuous.'
),
(
  'probability-chapter-3',
  'C3-18',
  110,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'The CDF of a discrete random variable',
  'has a staircase form, jumping at the values of positive probability mass',
  '["is continuously varying","has a staircase form, jumping at the values of positive probability mass","is always linear","has no jumps"]'::jsonb,
  'Each jump equals the probability mass at that value, and the CDF is continuous from the right.'
),
(
  'probability-chapter-3',
  'C3-19',
  111,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'For an integer-valued discrete random variable, the PMF is recovered from the CDF by',
  'p_X(k) = F_X(k) − F_X(k − 1)',
  '["p_X(k) = F_X(k) + F_X(k − 1)","p_X(k) = dF_X/dk","p_X(k) = F_X(k) − F_X(k − 1)","p_X(k) = F_X(k)/F_X(k − 1)"]'::jsonb,
  'Differencing the accumulated probability leaves the mass at k.'
),
(
  'probability-chapter-3',
  'C3-20',
  111,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'For a continuous random variable, the PDF is recovered from the CDF by',
  'differentiating: f_X(x) = dF_X/dx',
  '["summing the CDF values","integrating the CDF","dividing the CDF by x","differentiating: f_X(x) = dF_X/dx"]'::jsonb,
  'Integration builds the CDF from the PDF, so differentiation reverses it wherever the derivative exists.'
),
(
  'probability-chapter-3',
  'C3-21',
  110,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'Which pair of properties does every CDF have?',
  'It is monotonically nondecreasing, and tends to 0 as x → −∞ and to 1 as x → ∞',
  '["It is monotonically nondecreasing, and tends to 0 as x → −∞ and to 1 as x → ∞","It is strictly increasing and bounded by 1/2","It is nonincreasing and tends to 0 at both ends","It is symmetric about its mean"]'::jsonb,
  'Accumulating probability can never decrease, and the total accumulated is one.'
),
(
  'probability-chapter-3',
  'C3-22',
  111,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'The CDF of an exponential random variable with parameter λ, for x > 0, is',
  '1 − e^(−λx)',
  '["e^(−λx)","1 − e^(−λx)","λe^(−λx)","1 − λe^(−λx)"]'::jsonb,
  'Integrating λe^(−λt) from 0 to x gives 1 − e^(−λx).'
),
(
  'probability-chapter-3',
  'C3-23',
  111,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'The CDF of a geometric random variable with parameter p, at n = 1, 2, …, is',
  '1 − (1 − p)^n',
  '["(1 − p)^n","p(1 − p)^(n−1)","1 − (1 − p)^n","1 − p^n"]'::jsonb,
  'The geometric series for the first n masses sums to 1 − (1 − p)^n.'
),
(
  'probability-chapter-3',
  'C3-24',
  114,
  'section_4',
  'step_4',
  'Cumulative distribution functions',
  'For the maximum X of three independent scores, each uniform on 1…10, F_X(k) equals',
  '(k/10)³',
  '["3(k/10)","(k/10)/3","1 − (k/10)³","(k/10)³"]'::jsonb,
  'All three scores must be at most k, and independence multiplies the three probabilities.'
),
(
  'probability-chapter-3',
  'C3-25',
  114,
  'section_4',
  'step_5',
  'Normal random variables',
  'The PDF of a normal random variable with parameters μ and σ is',
  '(1/(√(2π)σ)) e^(−(x−μ)²/2σ²)',
  '["(1/(√(2π)σ)) e^(−(x−μ)²/2σ²)","(1/(√(2π)σ)) e^(−(x−μ)/2σ)","(1/σ) e^(−(x−μ)²/2)","(1/(√(2π))) e^(−x²/2σ²)"]'::jsonb,
  'The squared deviation in the exponent is what produces the bell shape around μ.'
),
(
  'probability-chapter-3',
  'C3-26',
  115,
  'section_4',
  'step_5',
  'Normal random variables',
  'For a normal random variable with parameters μ and σ',
  'E[X] = μ and var(X) = σ²',
  '["E[X] = 0 and var(X) = 1","E[X] = μ and var(X) = σ²","E[X] = μ and var(X) = σ","E[X] = σ and var(X) = μ²"]'::jsonb,
  'Symmetry gives the mean; a change of variables and integration by parts give the variance.'
),
(
  'probability-chapter-3',
  'C3-27',
  115,
  'section_4',
  'step_5',
  'Normal random variables',
  'If X is normal and Y = aX + b, then Y is',
  'normal, with mean aμ + b and variance a²σ²',
  '["normal, with mean μ + b and variance σ²","exponential, with parameter a","normal, with mean aμ + b and variance a²σ²","not necessarily a known distribution"]'::jsonb,
  'Normality is preserved by linear transformations, which is why standardizing works.'
),
(
  'probability-chapter-3',
  'C3-28',
  116,
  'section_4',
  'step_5',
  'Normal random variables',
  'A standard normal random variable is one with',
  'zero mean and unit variance',
  '["mean 1 and variance 1","mean 0 and variance 0","any mean and unit variance","zero mean and unit variance"]'::jsonb,
  'Its CDF is denoted Φ and is the function tabulated in the normal table.'
),
(
  'probability-chapter-3',
  'C3-29',
  116,
  'section_4',
  'step_5',
  'Normal random variables',
  'To standardize a normal random variable X with mean μ and variance σ², set Y equal to',
  '(X − μ)/σ',
  '["(X − μ)/σ","(X − μ)/σ²","X/σ − μ","(X + μ)/σ"]'::jsonb,
  'Subtracting the mean and dividing by the standard deviation gives mean 0 and variance 1.'
),
(
  'probability-chapter-3',
  'C3-30',
  116,
  'section_4',
  'step_5',
  'Normal random variables',
  'Because the standard normal table lists Φ(y) only for y ≥ 0, Φ(−0.5) is found as',
  '1 − Φ(0.5)',
  '["Φ(0.5)","1 − Φ(0.5)","−Φ(0.5)","1 + Φ(0.5)"]'::jsonb,
  'Symmetry of the PDF around zero turns a left tail into the complementary right tail.'
),
(
  'probability-chapter-3',
  'C3-31',
  117,
  'section_4',
  'step_5',
  'Normal random variables',
  'For X normal with mean μ and variance σ², P(X ≤ x) equals',
  'Φ((x − μ)/σ)',
  '["Φ(x − μ)","Φ(x/σ)","Φ((x − μ)/σ)","1 − Φ((x − μ)/σ)"]'::jsonb,
  'Standardize both sides of the inequality, then read the standard normal table.'
),
(
  'probability-chapter-3',
  'C3-32',
  117,
  'section_4',
  'step_5',
  'Normal random variables',
  'Annual snowfall is normal with μ = 60 and σ = 20 inches. Using Φ(1) = 0.8413, P(X ≥ 80) is',
  '0.1587',
  '["0.8413","0.3085","0.0228","0.1587"]'::jsonb,
  'Standardizing gives P(Y ≥ 1) = 1 − Φ(1) = 0.1587.'
),
(
  'probability-chapter-3',
  'C3-33',
  118,
  'section_4',
  'step_5',
  'Normal random variables',
  'Why does the normal distribution appear in so many models?',
  'The sum of many independent, identically distributed random variables has an approximately normal CDF',
  '["The sum of many independent, identically distributed random variables has an approximately normal CDF","Every random variable is normal in the limit of small samples","It is the only PDF that integrates to one","Products of independent random variables are normal"]'::jsonb,
  'This is the central limit theorem, which makes the normal a good model for additive effects.'
),
(
  'probability-chapter-3',
  'C3-34',
  118,
  'section_4',
  'step_5',
  'Normal random variables',
  'In the signal detection example with zero-mean noise of variance σ², the probability of error is',
  '1 − Φ(1/σ)',
  '["Φ(1/σ)","1 − Φ(1/σ)","1 − Φ(σ)","Φ(σ) − 1"]'::jsonb,
  'An error needs the noise to cross the distance 1, and both transmitted signals give the same probability by symmetry.'
),
(
  'probability-chapter-3',
  'C3-35',
  119,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'Conditioned on the event {X ∈ A} with P(X ∈ A) > 0, the conditional PDF is',
  'f_X(x)/P(X ∈ A) for x in A, and 0 otherwise',
  '["f_X(x)·P(X ∈ A) for x in A, and 0 otherwise","f_X(x) for x in A, and 0 otherwise","f_X(x)/P(X ∈ A) for x in A, and 0 otherwise","P(X ∈ A) for x in A, and 0 otherwise"]'::jsonb,
  'Dividing by P(X ∈ A) is what makes the conditional PDF integrate to one.'
),
(
  'probability-chapter-3',
  'C3-36',
  119,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'Inside the conditioning set, the conditional PDF',
  'has the same shape as the unconditional PDF, scaled by the constant 1/P(X ∈ A)',
  '["has a different shape from the unconditional PDF","is always uniform","is always zero","has the same shape as the unconditional PDF, scaled by the constant 1/P(X ∈ A)"]'::jsonb,
  'Only a vertical rescaling happens; outside the set the conditional PDF is zero.'
),
(
  'probability-chapter-3',
  'C3-37',
  120,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'The memorylessness property of the exponential says that, given that no event has occurred by time t, the remaining waiting time',
  'is exponential with the same parameter λ, whatever t is',
  '["is exponential with the same parameter λ, whatever t is","is exponential with parameter λt","becomes uniform on [0, t]","has mean t + 1/λ"]'::jsonb,
  'The conditional CDF works out to 1 − e^(−λx), independent of the elapsed time t.'
),
(
  'probability-chapter-3',
  'C3-38',
  121,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'The conditional expectation given an event A is',
  '∫_{−∞}^{∞} x f_{X|A}(x) dx',
  '["∫_{−∞}^{∞} x f_X(x) dx","∫_{−∞}^{∞} x f_{X|A}(x) dx","P(A)·E[X]","E[X]/P(A)"]'::jsonb,
  'It is the ordinary definition with the conditional PDF in place of the unconditional one.'
),
(
  'probability-chapter-3',
  'C3-39',
  121,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'If A_1, …, A_n are disjoint events of positive probability partitioning the sample space, then f_X(x) equals',
  'Σ_i P(A_i) f_{X|A_i}(x)',
  '["Σ_i f_{X|A_i}(x)","Π_i P(A_i) f_{X|A_i}(x)","Σ_i P(A_i) f_{X|A_i}(x)","Σ_i P(A_i)"]'::jsonb,
  'This is the total probability theorem written for densities.'
),
(
  'probability-chapter-3',
  'C3-40',
  121,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'The total expectation theorem for continuous random variables states that E[X] equals',
  'Σ_i P(A_i) E[X | A_i]',
  '["Σ_i E[X | A_i]","Σ_i P(A_i)","E[X | A_1] · … · E[X | A_n]","Σ_i P(A_i) E[X | A_i]"]'::jsonb,
  'Multiplying the total probability formula by x and integrating gives the weighted average of conditional means.'
),
(
  'probability-chapter-3',
  'C3-41',
  123,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'For the piecewise constant PDF equal to 1/3 on [0,1] and 2/3 on (1,2], the mean is',
  '7/6',
  '["7/6","1","3/2","11/36"]'::jsonb,
  'Divide and conquer: (1/3)(1/2) + (2/3)(3/2) = 7/6.'
),
(
  'probability-chapter-3',
  'C3-42',
  124,
  'section_4',
  'step_6',
  'Conditioning on an event',
  'You arrive uniformly between 7:10 and 7:30 for trains at 7:15 and 7:30. For 0 ≤ y ≤ 5, the waiting-time PDF f_Y(y) is',
  '1/10',
  '["1/20","1/10","1/5","1/15"]'::jsonb,
  'Total probability combines the two cases: (1/4)(1/5) + (3/4)(1/15) = 1/10.'
),
(
  'probability-chapter-3',
  'C3-43',
  124,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'Two random variables are jointly continuous when',
  'a nonnegative joint PDF exists whose integral over any region of the plane gives the probability of that region',
  '["each of them separately has a PDF","their joint CDF is linear","a nonnegative joint PDF exists whose integral over any region of the plane gives the probability of that region","they are independent"]'::jsonb,
  'Having marginal PDFs is not enough; the pair needs a joint density.'
),
(
  'probability-chapter-3',
  'C3-44',
  125,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'The joint PDF f_{X,Y}(a,c) is interpreted as',
  'probability per unit area near the point (a,c)',
  '["the probability that X = a and Y = c","probability per unit length near a","the joint CDF at (a,c)","probability per unit area near the point (a,c)"]'::jsonb,
  'For small δ, the probability of the δ-by-δ square at (a,c) is about f_{X,Y}(a,c)·δ².'
),
(
  'probability-chapter-3',
  'C3-45',
  125,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'The marginal PDF f_X is obtained from the joint PDF by',
  'integrating the joint PDF over y',
  '["integrating the joint PDF over y","differentiating the joint PDF with respect to y","dividing the joint PDF by f_Y","evaluating the joint PDF at y = 0"]'::jsonb,
  'Letting Y range over the whole line leaves only the dependence on x.'
),
(
  'probability-chapter-3',
  'C3-46',
  126,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'For a uniform joint PDF on a set S and any A ⊂ S, P((X,Y) ∈ A) equals',
  'area of A ∩ S divided by area of S',
  '["area of A divided by area of S","area of A ∩ S divided by area of S","area of S divided by area of A","1/area of S"]'::jsonb,
  'A uniform joint PDF makes probability proportional to area, exactly as the discrete uniform law counts outcomes.'
),
(
  'probability-chapter-3',
  'C3-47',
  127,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'In Buffon’s needle problem with needle length l and line spacing d (l < d), the probability of intersection is',
  '2l/(πd)',
  '["l/(πd)","πd/(2l)","2l/(πd)","l/d"]'::jsonb,
  'Integrating the uniform joint PDF over x ≤ (l/2)sin θ gives 2l/(πd), which also yields an experimental estimate of π.'
),
(
  'probability-chapter-3',
  'C3-48',
  128,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'For jointly continuous X and Y and scalars a, b, E[aX + bY] equals',
  'aE[X] + bE[Y]',
  '["abE[X]E[Y]","aE[X] + bE[Y] + E[XY]","(a + b)E[X + Y]","aE[X] + bE[Y]"]'::jsonb,
  'Expectation stays linear, whatever the dependence between X and Y.'
),
(
  'probability-chapter-3',
  'C3-49',
  128,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'The conditional PDF of X given Y = y is defined, for f_Y(y) > 0, as',
  'f_{X,Y}(x,y)/f_Y(y)',
  '["f_{X,Y}(x,y)/f_Y(y)","f_{X,Y}(x,y)·f_Y(y)","f_X(x)/f_Y(y)","f_{X,Y}(x,y)/f_X(x)"]'::jsonb,
  'It is the discrete formula p_{X|Y} = p_{X,Y}/p_Y with densities in place of masses.'
),
(
  'probability-chapter-3',
  'C3-50',
  128,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'For each fixed y with f_Y(y) > 0, the function x ↦ f_{X|Y}(x | y)',
  'integrates to 1 over x, so it is a legitimate PDF',
  '["integrates to f_Y(y)","integrates to 1 over x, so it is a legitimate PDF","sums to 1 over y","is always uniform"]'::jsonb,
  'Dividing by f_Y(y) is exactly the normalization that makes the slice a PDF.'
),
(
  'probability-chapter-3',
  'C3-51',
  133,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'The continuous Bayes rule expresses f_{X|Y}(x | y) as',
  'f_X(x)f_{Y|X}(y | x) divided by ∫ f_X(t)f_{Y|X}(y | t) dt',
  '["f_X(x)f_{Y|X}(y | x)","f_{Y|X}(y | x)/f_X(x)","f_X(x)f_{Y|X}(y | x) divided by ∫ f_X(t)f_{Y|X}(y | t) dt","f_X(x)/f_Y(y)"]'::jsonb,
  'The denominator is f_Y(y), computed by the total probability theorem for densities.'
),
(
  'probability-chapter-3',
  'C3-52',
  134,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'When the unobserved quantity X is discrete and the measurement Y is continuous, P(X = x | Y = y) equals',
  'p_X(x)f_{Y|X}(y | x)/f_Y(y)',
  '["p_X(x)f_{Y|X}(y | x)","f_{Y|X}(y | x)/p_X(x)","p_X(x)/f_Y(y)","p_X(x)f_{Y|X}(y | x)/f_Y(y)"]'::jsonb,
  'Conditioning on {y ≤ Y ≤ y + δ} and letting δ tend to zero cancels δ from numerator and denominator.'
),
(
  'probability-chapter-3',
  'C3-53',
  135,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'Two continuous random variables X and Y are independent exactly when',
  'f_{X,Y}(x,y) = f_X(x)f_Y(y) for all x, y',
  '["f_{X,Y}(x,y) = f_X(x)f_Y(y) for all x, y","f_{X,Y}(x,y) = f_X(x) + f_Y(y) for all x, y","E[XY] = E[X]E[Y]","their joint PDF is uniform"]'::jsonb,
  'Equivalently f_{X|Y}(x | y) = f_X(x) wherever f_Y(y) > 0: conditioning tells you nothing new.'
),
(
  'probability-chapter-3',
  'C3-54',
  136,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'If X and Y are independent, then var(X + Y) equals',
  'var(X) + var(Y)',
  '["var(X)·var(Y)","var(X) + var(Y)","var(X) + var(Y) + 2E[XY]","var(X) − var(Y)"]'::jsonb,
  'Independence also gives E[g(X)h(Y)] = E[g(X)]E[h(Y)] for any functions g and h.'
),
(
  'probability-chapter-3',
  'C3-55',
  136,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'The joint PDF is recovered from the joint CDF by',
  'taking the mixed second partial derivative ∂²F_{X,Y}/∂x∂y',
  '["integrating F_{X,Y} twice","differentiating F_{X,Y} with respect to x only","taking the mixed second partial derivative ∂²F_{X,Y}/∂x∂y","dividing F_{X,Y} by xy"]'::jsonb,
  'Two integrations build the CDF from the PDF, so two differentiations reverse them.'
),
(
  'probability-chapter-3',
  'C3-56',
  137,
  'section_4',
  'step_7',
  'Multiple continuous random variables',
  'For three random variables, the multiplication rule reads',
  'f_{X,Y,Z}(x,y,z) = f_{X|Y,Z}(x | y,z) f_{Y|Z}(y | z) f_Z(z)',
  '["f_{X,Y,Z}(x,y,z) = f_X(x) f_Y(y) f_Z(z)","f_{X,Y,Z}(x,y,z) = f_{X|Y,Z}(x | y,z) f_Z(z)","f_{X,Y,Z}(x,y,z) = f_{X,Y}(x,y) + f_Z(z)","f_{X,Y,Z}(x,y,z) = f_{X|Y,Z}(x | y,z) f_{Y|Z}(y | z) f_Z(z)"]'::jsonb,
  'The product of marginals holds only under independence; the chain rule holds always.'
),
(
  'probability-chapter-3',
  'C3-57',
  138,
  'section_4',
  'step_8',
  'Derived distributions',
  'The two-step method for finding the PDF of Y = g(X) is',
  'compute the CDF F_Y(y) = P(g(X) ≤ y), then differentiate it',
  '["compute the CDF F_Y(y) = P(g(X) ≤ y), then differentiate it","compute E[g(X)], then differentiate it","substitute y for x in f_X","integrate f_X over the range of g"]'::jsonb,
  'The event {g(X) ≤ y} must first be translated into an event about X.'
),
(
  'probability-chapter-3',
  'C3-58',
  138,
  'section_4',
  'step_8',
  'Derived distributions',
  'For X uniform on [0,1] and Y = √X, the PDF of Y on [0,1] is',
  '2y',
  '["1/(2√y)","2y","y²","1"]'::jsonb,
  'F_Y(y) = P(X ≤ y²) = y², and differentiating gives 2y.'
),
(
  'probability-chapter-3',
  'C3-59',
  139,
  'section_4',
  'step_8',
  'Derived distributions',
  'A 180-mile trip is driven at a speed uniform on [30,60]. The PDF of the duration Y on [3,6] is',
  '6/y²',
  '["1/30","y/6","6/y²","6/y"]'::jsonb,
  'F_Y(y) = 2 − 6/y on that range, and differentiating gives 6/y².'
),
(
  'probability-chapter-3',
  'C3-60',
  140,
  'section_4',
  'step_8',
  'Derived distributions',
  'For Y = aX + b with a ≠ 0, the PDF of Y is',
  '(1/|a|) f_X((y − b)/a)',
  '["a f_X(ay + b)","(1/a²) f_X((y − b)/a)","f_X(y − b)","(1/|a|) f_X((y − b)/a)"]'::jsonb,
  'The PDF is stretched horizontally by a and scaled vertically by 1/|a| so the area stays one.'
),
(
  'probability-chapter-3',
  'C3-61',
  142,
  'section_4',
  'step_8',
  'Derived distributions',
  'A linear function of a normal random variable is',
  'normal, with mean aμ + b and variance a²σ²',
  '["normal, with mean aμ + b and variance a²σ²","exponential","uniform","normal, with mean μ and variance σ²"]'::jsonb,
  'Substituting into the linear-case formula reproduces a normal PDF with those parameters.'
),
(
  'probability-chapter-3',
  'C3-62',
  144,
  'section_4',
  'step_8',
  'Derived distributions',
  'For strictly monotonic g with inverse h, the PDF of Y = g(X) is',
  'f_X(h(y))·|dh/dy(y)|',
  '["f_X(h(y))","f_X(h(y))·|dh/dy(y)|","f_X(y)·|dh/dy(y)|","f_X(h(y))/|dg/dx(y)|"]'::jsonb,
  'The derivative factor accounts for how the transformation stretches an interval.'
),
(
  'probability-chapter-3',
  'C3-63',
  146,
  'section_4',
  'step_8',
  'Derived distributions',
  'For X uniform on (0,1] and Y = X², the PDF of Y on (0,1] is',
  '1/(2√y)',
  '["2y","√y","1/(2√y)","1"]'::jsonb,
  'Here h(y) = √y, so |dh/dy| = 1/(2√y) and f_X(√y) = 1.'
),
(
  'probability-chapter-3',
  'C3-64',
  146,
  'section_4',
  'step_8',
  'Derived distributions',
  'For independent X and Y uniform on [0,1], the PDF of Z = max{X,Y} on [0,1] is',
  '2z',
  '["z²","1/2","1","2z"]'::jsonb,
  'Independence gives F_Z(z) = P(X ≤ z)P(Y ≤ z) = z², and differentiating gives 2z.'
),
(
  'probability-chapter-3',
  'C3-65',
  149,
  'section_4',
  'step_8',
  'Derived distributions',
  'For independent exponentials X and Y with parameter λ, the PDF of Z = X − Y is',
  '(λ/2)e^(−λ|z|), the two-sided exponential or Laplace PDF',
  '["(λ/2)e^(−λ|z|), the two-sided exponential or Laplace PDF","λe^(−λz) for z ≥ 0 and 0 otherwise","(λ/2)e^(−λz) for all z","uniform on the real line"]'::jsonb,
  'Symmetry between X − Y and Y − X makes the CDF, and hence the PDF, symmetric about zero.'
),
(
  'probability-chapter-3',
  'C3-66',
  150,
  'section_4',
  'step_8',
  'Derived distributions',
  'Which summary of the special continuous laws is correct?',
  'Uniform on [a,b] has variance (b − a)²/12, exponential with parameter λ has variance 1/λ², and normal with parameters μ and σ² has variance σ²',
  '["Uniform on [a,b] has variance (b − a)/12, exponential has variance 1/λ, and normal has variance σ","Uniform on [a,b] has variance (b − a)²/12, exponential with parameter λ has variance 1/λ², and normal with parameters μ and σ² has variance σ²","Uniform on [a,b] has variance (b + a)²/12, exponential has variance λ², and normal has variance μ","All three laws have variance equal to their mean"]'::jsonb,
  'These are the means and variances derived in the chapter and collected in its summary.'
)
ON CONFLICT (deck_id, source_id) DO UPDATE SET
  source_page = EXCLUDED.source_page,
  section = EXCLUDED.section,
  step = EXCLUDED.step,
  step_title = EXCLUDED.step_title,
  japanese_word = EXCLUDED.japanese_word,
  english = EXCLUDED.english,
  authored_options = EXCLUDED.authored_options,
  explanation = EXCLUDED.explanation;
