INSERT INTO public.learning_decks (
  id, title, description, question_label, answer_label, question_format
) VALUES (
  'probability-chapter-2',
  'Probability · Discrete Random Variables',
  'Learn discrete random variables, probability mass functions, standard distributions, transformations, expectation, variance, conditioning and independence.',
  'Question',
  'Answer',
  'multiple_choice'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  question_label = EXCLUDED.question_label,
  answer_label = EXCLUDED.answer_label,
  question_format = EXCLUDED.question_format;

INSERT INTO public.words10k (
  deck_id,
  source_id,
  source_page,
  section,
  step,
  step_title,
  japanese_word,
  english,
  authored_options,
  explanation
) VALUES
(
  'probability-chapter-2',
  'C2-N01',
  59,
  'section_3',
  'step_1',
  'Notation',
  'X',
  'A random variable',
  '["A random variable","A fixed numerical value","A sample space","An event"]'::jsonb,
  'Uppercase letters such as X conventionally name random variables.'
),
(
  'probability-chapter-2',
  'C2-N02',
  59,
  'section_3',
  'step_1',
  'Notation',
  'x',
  'A possible numerical value of X',
  '["The random variable itself","The probability of X","The sample space","A possible numerical value of X"]'::jsonb,
  'Lowercase letters such as x conventionally denote numerical values a random variable can take.'
),
(
  'probability-chapter-2',
  'C2-N03',
  58,
  'section_3',
  'step_1',
  'Notation',
  'p_X(x)',
  'The probability that X equals x',
  '["The expected value of X","The variance of X","The probability that X equals x","The probability that X is not x"]'::jsonb,
  'The PMF assigns probability mass p_X(x) to the value x.'
),
(
  'probability-chapter-2',
  'C2-N04',
  58,
  'section_3',
  'step_1',
  'Notation',
  'p_X(x) = P(X = x)',
  'The definition of the PMF at x',
  '["A formula for variance","The definition of the PMF at x","The definition of the mean","A test for independence"]'::jsonb,
  'Both sides are the probability of the event that X takes the value x.'
),
(
  'probability-chapter-2',
  'C2-N05',
  59,
  'section_3',
  'step_1',
  'Notation',
  'Σ_x p_X(x) = 1',
  'All probability masses add to 1',
  '["All probability masses add to 1","Every value of X has probability 1","The mean of X is 1","X can take only one value"]'::jsonb,
  'The events {X = x} partition the sample space, so their probabilities sum to 1.'
),
(
  'probability-chapter-2',
  'C2-N06',
  59,
  'section_3',
  'step_1',
  'Notation',
  'P(X ∈ S) = Σ_{x ∈ S} p_X(x)',
  'Add the masses of the values in S',
  '["Multiply the masses of the values in S","Average all values in S","Add the values in S without their probabilities","Add the masses of the values in S"]'::jsonb,
  'An event defined by a set of values is evaluated by summing the PMF over those values.'
),
(
  'probability-chapter-2',
  'C2-N07',
  66,
  'section_3',
  'step_1',
  'Notation',
  'E[X]',
  'The expected value or mean of X',
  '["The range of X","The standard deviation of X","The expected value or mean of X","The event that X occurs"]'::jsonb,
  'E[X] is the probability-weighted average of the possible values of X.'
),
(
  'probability-chapter-2',
  'C2-N08',
  69,
  'section_3',
  'step_1',
  'Notation',
  'E[g(X)] = Σ_x g(x)p_X(x)',
  'The expected value rule for a function of X',
  '["The independence test for X and Y","The expected value rule for a function of X","The PMF normalization rule","The definition of conditional probability"]'::jsonb,
  'The expectation of g(X) can be computed directly from the PMF of X.'
),
(
  'probability-chapter-2',
  'C2-N09',
  70,
  'section_3',
  'step_1',
  'Notation',
  'var(X)',
  'The variance of X',
  '["The variance of X","The range of X","The mean of X","The PMF of X"]'::jsonb,
  'Variance measures the expected squared distance from the mean.'
),
(
  'probability-chapter-2',
  'C2-N10',
  70,
  'section_3',
  'step_1',
  'Notation',
  'σ_X = √var(X)',
  'The standard deviation of X',
  '["The second moment of X","The mean of X","The conditional variance of X","The standard deviation of X"]'::jsonb,
  'Standard deviation is the nonnegative square root of variance.'
),
(
  'probability-chapter-2',
  'C2-N11',
  71,
  'section_3',
  'step_1',
  'Notation',
  'var(X) = E[X²] − (E[X])²',
  'Variance expressed using moments',
  '["The mean of a product","The total expectation theorem","Variance expressed using moments","The PMF of X"]'::jsonb,
  'Variance equals the second moment minus the square of the first moment.'
),
(
  'probability-chapter-2',
  'C2-N12',
  76,
  'section_3',
  'step_1',
  'Notation',
  'p_{X,Y}(x,y)',
  'The joint PMF of X and Y',
  '["The conditional mean of X given Y","The joint PMF of X and Y","The product of X and Y","The PMF of X only"]'::jsonb,
  'It is the probability that X = x and Y = y simultaneously.'
),
(
  'probability-chapter-2',
  'C2-N13',
  77,
  'section_3',
  'step_1',
  'Notation',
  'p_X(x) = Σ_y p_{X,Y}(x,y)',
  'Marginalize the joint PMF over y',
  '["Marginalize the joint PMF over y","Condition X on Y","Prove X and Y are independent","Calculate the variance of X"]'::jsonb,
  'Summing a joint PMF over all possible y values leaves the marginal PMF of X.'
),
(
  'probability-chapter-2',
  'C2-N14',
  81,
  'section_3',
  'step_1',
  'Notation',
  'p_{X|A}(x)',
  'The conditional PMF of X given event A',
  '["The joint PMF of X and A","The probability of A given X","The PMF of X outside A","The conditional PMF of X given event A"]'::jsonb,
  'The vertical bar indicates that the probability model has been conditioned on event A.'
),
(
  'probability-chapter-2',
  'C2-N15',
  82,
  'section_3',
  'step_1',
  'Notation',
  'p_{X|Y}(x|y)',
  'The conditional PMF of X given Y = y',
  '["The joint PMF at (x,y)","The product of the marginal PMFs","The conditional PMF of X given Y = y","The conditional PMF of Y given X = x"]'::jsonb,
  'It describes the distribution of X after the value Y = y is known.'
),
(
  'probability-chapter-2',
  'C2-N16',
  87,
  'section_3',
  'step_1',
  'Notation',
  'E[X | Y = y]',
  'The conditional expectation of X given Y = y',
  '["The expectation of Y given X","The conditional expectation of X given Y = y","The probability that X equals y","The joint expectation of X and Y"]'::jsonb,
  'It is the mean of X calculated using the conditional PMF p_{X|Y}(x|y).'
),
(
  'probability-chapter-2',
  'C2-01',
  56,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'Which statement defines a random variable?',
  'A real-valued function of an experimental outcome',
  '["A real-valued function of an experimental outcome","A randomly selected event","A probability assigned to the sample space","A list of outcomes in time order"]'::jsonb,
  'A random variable maps each outcome in the sample space to one real number.'
),
(
  'probability-chapter-2',
  'C2-02',
  56,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'Which is a random variable for five coin tosses?',
  'The number of heads',
  '["The sequence HHTHT","The set {H,T}","The instruction to toss five times","The number of heads"]'::jsonb,
  'The number of heads is numerical. A raw heads-and-tails sequence has no explicit numerical value.'
),
(
  'probability-chapter-2',
  'C2-03',
  57,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'When is a random variable discrete?',
  'Its range is finite or countably infinite',
  '["Every outcome has the same probability","It can take only positive values","Its range is finite or countably infinite","Its range contains every real number"]'::jsonb,
  'Discreteness concerns the set of possible numerical values, not whether their probabilities are equal or their signs are positive.'
),
(
  'probability-chapter-2',
  'C2-04',
  57,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'A point a is selected from [−1,1], and X = sgn(a). Why is X discrete?',
  'X can take only −1, 0, or 1',
  '["X is always positive","X can take only −1, 0, or 1","The interval [−1,1] is finite","Every value of a is equally likely"]'::jsonb,
  'Although the underlying outcome can vary continuously, the range of X has only three values.'
),
(
  'probability-chapter-2',
  'C2-05',
  59,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'Which pair of conditions must every PMF satisfy?',
  'p_X(x) ≥ 0 and Σ_x p_X(x) = 1',
  '["p_X(x) ≥ 0 and Σ_x p_X(x) = 1","p_X(x) > 0 and Σ_x p_X(x) = 0","p_X(x) ≤ 1 and Σ_x x = 1","p_X(x) = x and Σ_x x = 0"]'::jsonb,
  'Probability masses are nonnegative and must sum to one across all possible values.'
),
(
  'probability-chapter-2',
  'C2-06',
  58,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'Two fair coins are tossed and X is the number of heads. What is p_X(1)?',
  '1/2',
  '["1/4","3/4","1","1/2"]'::jsonb,
  'Exactly one head occurs for HT or TH, two of the four equally likely outcomes.'
),
(
  'probability-chapter-2',
  'C2-07',
  59,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'If p_X(−1)=0.2, p_X(0)=0.5, and p_X(1)=0.3, what is P(X ≥ 0)?',
  '0.8',
  '["0.3","1.0","0.8","0.5"]'::jsonb,
  'Add the masses at 0 and 1: 0.5 + 0.3 = 0.8.'
),
(
  'probability-chapter-2',
  'C2-08',
  60,
  'section_3',
  'step_2',
  'Random variables and PMFs',
  'Two fair 4-sided dice are rolled and X is their maximum. What is p_X(2)?',
  '3/16',
  '["7/16","3/16","1/16","4/16"]'::jsonb,
  'The outcomes (1,2), (2,1), and (2,2) have maximum 2, each with probability 1/16.'
),
(
  'probability-chapter-2',
  'C2-09',
  59,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'A Bernoulli random variable uses which two numerical values?',
  '0 and 1',
  '["0 and 1","−1 and 1","0 and n","Any two consecutive integers"]'::jsonb,
  'A Bernoulli variable encodes failure as 0 and success as 1.'
),
(
  'probability-chapter-2',
  'C2-10',
  59,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'For a Bernoulli variable with success probability p, what is p_X(0)?',
  '1 − p',
  '["p","p²","0","1 − p"]'::jsonb,
  'The two outcomes exhaust the sample space, so the failure probability is 1 − p.'
),
(
  'probability-chapter-2',
  'C2-11',
  61,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'Which experiment produces a binomial random variable with parameters n and p?',
  'Count successes in n independent trials with success probability p',
  '["Count events in a fixed interval with rate p","Record one success or failure only","Count successes in n independent trials with success probability p","Count trials until the first success"]'::jsonb,
  'A binomial variable counts successes across a fixed number of independent Bernoulli trials.'
),
(
  'probability-chapter-2',
  'C2-12',
  61,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'Three fair coins are tossed. What is the probability of exactly two heads?',
  '3/8',
  '["3/4","3/8","1/8","1/2"]'::jsonb,
  'There are C(3,2)=3 sequences with two heads, and each has probability 1/8.'
),
(
  'probability-chapter-2',
  'C2-13',
  61,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'A geometric random variable counts:',
  'Trials up to and including the first success',
  '["Trials up to and including the first success","Successes in a fixed number of trials","Failures after the first success","Events in a fixed time interval"]'::jsonb,
  'Its possible values are 1,2,… because at least one trial is required.'
),
(
  'probability-chapter-2',
  'C2-14',
  61,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'Independent trials succeed with probability 0.2. What is P(the first success occurs on trial 3)?',
  '0.128',
  '["0.032","0.160","0.512","0.128"]'::jsonb,
  'Two failures followed by success has probability (0.8)²(0.2)=0.128.'
),
(
  'probability-chapter-2',
  'C2-15',
  62,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'What is the PMF of a Poisson random variable with parameter λ?',
  'p_X(k)=e^(−λ)λ^k/k!, k=0,1,…',
  '["p_X(k)=C(n,k)λ^k(1−λ)^(n−k)","p_X(k)=1/λ for k=1,…,λ","p_X(k)=e^(−λ)λ^k/k!, k=0,1,…","p_X(k)=(1−λ)^(k−1)λ, k=1,2,…"]'::jsonb,
  'The Poisson PMF assigns mass e^(−λ)λ^k/k! to each nonnegative integer k.'
),
(
  'probability-chapter-2',
  'C2-16',
  63,
  'section_3',
  'step_3',
  'Standard discrete distributions',
  'When is a Poisson(λ) model a useful approximation to Binomial(n,p)?',
  'n is large, p is small, and λ=np',
  '["p=1/2 and λ=n²","n is large, p is small, and λ=np","n is small, p is near 1, and λ=n+p","n=p and λ=1"]'::jsonb,
  'Rare successes across many trials lead to the Poisson approximation with the same mean np.'
),
(
  'probability-chapter-2',
  'C2-17',
  64,
  'section_3',
  'step_4',
  'Functions of random variables',
  'If Y=g(X), how is p_Y(y) obtained from p_X?',
  'Sum p_X(x) over every x with g(x)=y',
  '["Sum p_X(x) over every x with g(x)=y","Use only the smallest x with g(x)=y","Multiply p_X(x) over every x with g(x)=y","Replace every x in p_X(x) by y"]'::jsonb,
  'All input values that map to the same output y contribute their probability mass.'
),
(
  'probability-chapter-2',
  'C2-18',
  64,
  'section_3',
  'step_4',
  'Functions of random variables',
  'X is uniform on {−2,−1,0,1,2} and Y=|X|. What is P(Y=1)?',
  '2/5',
  '["1/5","3/5","4/5","2/5"]'::jsonb,
  'Y=1 arises from X=−1 or X=1, so the two masses add to 2/5.'
),
(
  'probability-chapter-2',
  'C2-19',
  64,
  'section_3',
  'step_4',
  'Functions of random variables',
  'If Y=X², which X values contribute to p_Y(9)?',
  'X=−3 and X=3',
  '["X=−9 and X=9","X=9 only","X=−3 and X=3","X=3 only"]'::jsonb,
  'Both −3 and 3 square to 9, so both preimages contribute.'
),
(
  'probability-chapter-2',
  'C2-20',
  64,
  'section_3',
  'step_4',
  'Functions of random variables',
  'If p_X(−3)=0.2 and p_X(3)=0.5, and Y=X², what is p_Y(9)?',
  '0.7',
  '["0.5","0.7","0.3","0.1"]'::jsonb,
  'The event {Y=9} is the union of {X=−3} and {X=3}, so 0.2+0.5=0.7.'
),
(
  'probability-chapter-2',
  'C2-21',
  63,
  'section_3',
  'step_4',
  'Functions of random variables',
  'X takes values 1,2,3 and Y=2X+1. What is the range of Y?',
  '{3,5,7}',
  '["{3,5,7}","{2,4,6}","{1,2,3}","{3,4,5}"]'::jsonb,
  'Apply the function 2x+1 to each possible input value.'
),
(
  'probability-chapter-2',
  'C2-22',
  64,
  'section_3',
  'step_4',
  'Functions of random variables',
  'If g is one-to-one on the range of X and y=g(x), then:',
  'p_Y(y)=p_X(x)',
  '["p_Y(y)=1−p_X(x)","p_Y(y)=p_X(x)²","p_Y(y)=0","p_Y(y)=p_X(x)"]'::jsonb,
  'A one-to-one mapping gives y exactly one preimage, so its mass is carried over unchanged.'
),
(
  'probability-chapter-2',
  'C2-23',
  64,
  'section_3',
  'step_4',
  'Functions of random variables',
  'X has p_X(0)=0.25 and p_X(1)=0.75. If Y=5 for both X values, what is p_Y(5)?',
  '1',
  '["0.25","0.1875","1","0.75"]'::jsonb,
  'Every possible value of X maps to 5, so all probability mass is collected at Y=5.'
),
(
  'probability-chapter-2',
  'C2-24',
  64,
  'section_3',
  'step_4',
  'Functions of random variables',
  'Why can distinct X values have the same transformed value Y=g(X)?',
  'A function need not be one-to-one',
  '["Y must have a larger range than X","A function need not be one-to-one","A PMF may contain negative values","Random variables cannot share outcomes"]'::jsonb,
  'Many-to-one transformations combine the probability masses of several X values.'
),
(
  'probability-chapter-2',
  'C2-25',
  66,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'X takes 0 with probability 0.4 and 10 with probability 0.6. What is E[X]?',
  '6',
  '["6","4","5","10"]'::jsonb,
  'The probability-weighted average is 0(0.4)+10(0.6)=6.'
),
(
  'probability-chapter-2',
  'C2-26',
  66,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'Which description best matches E[X]?',
  'A probability-weighted average of X''s possible values',
  '["The most likely value of X","The largest value of X","The probability that X is positive","A probability-weighted average of X''s possible values"]'::jsonb,
  'The mean need not be a possible value or the most likely value.'
),
(
  'probability-chapter-2',
  'C2-27',
  69,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'X takes −1 and 1 with equal probability. What are E[X] and E[X²]?',
  'E[X]=0 and E[X²]=1',
  '["E[X]=0 and E[X²]=0","E[X]=−1 and E[X²]=1","E[X]=0 and E[X²]=1","E[X]=1 and E[X²]=1"]'::jsonb,
  'The signs cancel in E[X], while both squared values equal 1.'
),
(
  'probability-chapter-2',
  'C2-28',
  71,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'X has E[X]=3 and E[X²]=13. What is var(X)?',
  '4',
  '["22","4","10","16"]'::jsonb,
  'Use var(X)=E[X²]−(E[X])²=13−9=4.'
),
(
  'probability-chapter-2',
  'C2-29',
  70,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'Why is variance always nonnegative?',
  'It is an expectation of squared deviations',
  '["It is an expectation of squared deviations","Every random variable is nonnegative","The mean is always zero","Probabilities can be negative"]'::jsonb,
  'Each squared distance (X−E[X])² is nonnegative, so its expectation is nonnegative.'
),
(
  'probability-chapter-2',
  'C2-30',
  70,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'Which measure has the same physical units as X?',
  'Standard deviation',
  '["Variance","Second moment","Squared deviation","Standard deviation"]'::jsonb,
  'Variance has squared units; taking its square root restores the units of X.'
),
(
  'probability-chapter-2',
  'C2-31',
  70,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'If Y=4X−3 and E[X]=2, what is E[Y]?',
  '5',
  '["11","−4","5","8"]'::jsonb,
  'Linearity gives E[Y]=4E[X]−3=8−3=5.'
),
(
  'probability-chapter-2',
  'C2-32',
  71,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'If Y=4X−3 and var(X)=2, what is var(Y)?',
  '32',
  '["2","32","8","5"]'::jsonb,
  'Adding a constant does not change variance, while scaling by 4 multiplies variance by 4².'
),
(
  'probability-chapter-2',
  'C2-33',
  71,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'For a Bernoulli(p) random variable, which mean and variance are correct?',
  'E[X]=p and var(X)=p(1−p)',
  '["E[X]=p and var(X)=p(1−p)","E[X]=1−p and var(X)=p","E[X]=p² and var(X)=1−p","E[X]=0 and var(X)=p²"]'::jsonb,
  'A Bernoulli variable is 1 with probability p and 0 otherwise.'
),
(
  'probability-chapter-2',
  'C2-34',
  72,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'X is discrete uniform on the integers from 2 through 8. What is E[X]?',
  '5',
  '["4","6","10","5"]'::jsonb,
  'For a discrete uniform variable on consecutive integers a through b, the mean is (a+b)/2.'
),
(
  'probability-chapter-2',
  'C2-35',
  73,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'X is discrete uniform on the integers from 2 through 8. What is var(X)?',
  '4',
  '["7/12","16","4","5"]'::jsonb,
  'For consecutive integers a through b, var(X)=(b−a)(b−a+2)/12=(6·8)/12=4.'
),
(
  'probability-chapter-2',
  'C2-36',
  74,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'For a Poisson(λ) random variable, which mean and variance are correct?',
  'E[X]=λ and var(X)=λ',
  '["E[X]=λ and var(X)=λ²","E[X]=λ and var(X)=λ","E[X]=1/λ and var(X)=1/λ²","E[X]=λ² and var(X)=λ"]'::jsonb,
  'Both the mean and variance of a Poisson random variable equal its parameter λ.'
),
(
  'probability-chapter-2',
  'C2-37',
  89,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'A geometric random variable has success probability p=0.25. What are its mean and variance?',
  'E[X]=4 and var(X)=12',
  '["E[X]=4 and var(X)=12","E[X]=4 and var(X)=4","E[X]=0.25 and var(X)=0.1875","E[X]=3 and var(X)=4"]'::jsonb,
  'For the trial count through first success, E[X]=1/p=4 and var(X)=(1−p)/p²=12.'
),
(
  'probability-chapter-2',
  'C2-38',
  69,
  'section_3',
  'step_5',
  'Expectation, mean, and variance',
  'X takes −1 with probability 0.25 and 2 with probability 0.75. What is E[X²]?',
  '3.25',
  '["1.25","2.5","4","3.25"]'::jsonb,
  'Use the expected value rule: E[X²]=(−1)²(0.25)+2²(0.75)=0.25+3=3.25.'
),
(
  'probability-chapter-2',
  'C2-39',
  76,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'What does p_{X,Y}(x,y) equal?',
  'P(X=x and Y=y)',
  '["P(X=x) + P(Y=y)","P(X=x | Y=y)","P(X=x and Y=y)","P(X=x or Y=y)"]'::jsonb,
  'A joint PMF assigns probability to simultaneous pairs of values.'
),
(
  'probability-chapter-2',
  'C2-40',
  76,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'What must the sum of p_{X,Y}(x,y) over all x and y equal?',
  '1',
  '["p_X(x)p_Y(y)","1","0","E[X]+E[Y]"]'::jsonb,
  'All possible value pairs partition the sample space.'
),
(
  'probability-chapter-2',
  'C2-41',
  77,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'A joint PMF has p(0,0)=0.1, p(0,1)=0.2, p(1,0)=0.3, p(1,1)=0.4. What is p_X(1)?',
  '0.7',
  '["0.7","0.4","0.3","0.6"]'::jsonb,
  'Sum across both Y values in the X=1 row: 0.3+0.4=0.7.'
),
(
  'probability-chapter-2',
  'C2-42',
  77,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'Using the same joint PMF, what is P(X=Y)?',
  '0.5',
  '["0.7","0.3","1.0","0.5"]'::jsonb,
  'The equal pairs are (0,0) and (1,1), with masses 0.1+0.4=0.5.'
),
(
  'probability-chapter-2',
  'C2-43',
  78,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'How is E[g(X,Y)] computed from a joint PMF?',
  'Σ_x Σ_y g(x,y)p_{X,Y}(x,y)',
  '["g(E[X],E[Y]) in every case","Σ_x Σ_y p_X(x)p_Y(y) without g","Σ_x Σ_y g(x,y)p_{X,Y}(x,y)","Σ_x g(x,x)p_X(x)"]'::jsonb,
  'Weight g(x,y) by the probability of every possible pair and add.'
),
(
  'probability-chapter-2',
  'C2-44',
  78,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'Does E[X+Y]=E[X]+E[Y] require X and Y to be independent?',
  'No',
  '["Only if X and Y have the same PMF","No","Yes","Only if X and Y are Bernoulli"]'::jsonb,
  'Linearity of expectation holds for any jointly distributed X and Y.'
),
(
  'probability-chapter-2',
  'C2-45',
  79,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'Let X_i indicate whether student i succeeds, with P(X_i=1)=p. For X=Σ_i X_i over n students, what is E[X]?',
  'np',
  '["np","p/n","n+p","p^n"]'::jsonb,
  'Each indicator has mean p, and linearity gives E[X]=Σ_i E[X_i]=np.'
),
(
  'probability-chapter-2',
  'C2-46',
  79,
  'section_3',
  'step_6',
  'Joint PMFs and multiple variables',
  'n people randomly retrieve hats. Let X be the number who get their own hat. What is E[X]?',
  '1',
  '["n","1/n","0","1"]'::jsonb,
  'Each person has probability 1/n of getting their own hat; summing n indicator means gives n(1/n)=1.'
),
(
  'probability-chapter-2',
  'C2-47',
  81,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'For P(A)>0, which formula gives the conditional PMF of X given A?',
  'p_{X|A}(x)=P(X=x and A)/P(A)',
  '["p_{X|A}(x)=P(A)/p_X(x)","p_{X|A}(x)=p_X(x)+P(A)","p_{X|A}(x)=P(X=x and A)/P(A)","p_{X|A}(x)=p_X(x)P(A)"]'::jsonb,
  'Conditioning restricts the probability model to A and renormalizes by P(A).'
),
(
  'probability-chapter-2',
  'C2-48',
  81,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'What must Σ_x p_{X|A}(x) equal?',
  '1',
  '["E[X|A]","1","P(A)","0"]'::jsonb,
  'For a fixed conditioning event with positive probability, a conditional PMF is an ordinary normalized PMF.'
),
(
  'probability-chapter-2',
  'C2-49',
  82,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'Which formula relates a conditional PMF to a joint PMF?',
  'p_{X|Y}(x|y)=p_{X,Y}(x,y)/p_Y(y)',
  '["p_{X|Y}(x|y)=p_{X,Y}(x,y)/p_Y(y)","p_{X|Y}(x|y)=p_X(x)/p_Y(y)","p_{X|Y}(x|y)=p_{X,Y}(x,y)p_Y(y)","p_{X|Y}(x|y)=p_Y(y)/p_X(x)"]'::jsonb,
  'The formula applies when p_Y(y)>0.'
),
(
  'probability-chapter-2',
  'C2-50',
  83,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'Which multiplication rule reconstructs the joint PMF?',
  'p_{X,Y}(x,y)=p_Y(y)p_{X|Y}(x|y)',
  '["p_{X,Y}(x,y)=p_X(x)+p_Y(y)","p_{X,Y}(x,y)=p_{X|Y}(x|y)/p_Y(y)","p_{X,Y}(x,y)=p_X(x)−p_Y(y)","p_{X,Y}(x,y)=p_Y(y)p_{X|Y}(x|y)"]'::jsonb,
  'Multiply the probability of the conditioning value by the conditional probability of X.'
),
(
  'probability-chapter-2',
  'C2-51',
  85,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'Y equals 0 or 1 with probability 1/2 each. If P(X=1|Y=0)=0.2 and P(X=1|Y=1)=0.8, what is P(X=1)?',
  '0.5',
  '["0.8","1.0","0.5","0.4"]'::jsonb,
  'Total probability gives 0.5(0.2)+0.5(0.8)=0.5.'
),
(
  'probability-chapter-2',
  'C2-52',
  87,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'How is E[X|Y=y] calculated?',
  'Σ_x x p_{X|Y}(x|y)',
  '["E[X]/p_Y(y)","Σ_x x p_{X|Y}(x|y)","Σ_y y p_Y(y)","Σ_x p_X(x)"]'::jsonb,
  'Conditional expectation is the mean under the conditional PMF for the specified y.'
),
(
  'probability-chapter-2',
  'C2-53',
  88,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'Y is equally likely to be 0 or 1. If E[X|Y=0]=2 and E[X|Y=1]=6, what is E[X]?',
  '4',
  '["4","8","3","2"]'::jsonb,
  'Total expectation gives 0.5(2)+0.5(6)=4.'
),
(
  'probability-chapter-2',
  'C2-54',
  89,
  'section_3',
  'step_7',
  'Conditioning and conditional expectation',
  'For a geometric random variable counting trials until first success with success probability p, what is E[X]?',
  '1/p',
  '["p","1−p","p/(1−p)","1/p"]'::jsonb,
  'After a failed first trial the process restarts, yielding E[X]=p·1+(1−p)(1+E[X])=1/p.'
),
(
  'probability-chapter-2',
  'C2-55',
  90,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'X is independent of event A with P(A)>0 when:',
  'p_{X|A}(x)=p_X(x) for every x',
  '["X can take only one value","A has probability 1","p_{X|A}(x)=p_X(x) for every x","p_{X|A}(x)=P(A) for every x"]'::jsonb,
  'Knowing that A occurred must leave the entire PMF of X unchanged.'
),
(
  'probability-chapter-2',
  'C2-56',
  91,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'Which identity defines independence of X and Y?',
  'p_{X,Y}(x,y)=p_X(x)p_Y(y) for all x,y',
  '["E[X]=E[Y]","p_{X,Y}(x,y)=p_X(x)p_Y(y) for all x,y","p_{X,Y}(x,y)=p_X(x)+p_Y(y) for all x,y","p_X(x)=p_Y(y) for all x,y"]'::jsonb,
  'The joint mass must factor into the two marginal masses at every pair.'
),
(
  'probability-chapter-2',
  'C2-57',
  91,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'If X and Y are independent and p_Y(y)>0, what is p_{X|Y}(x|y)?',
  'p_X(x)',
  '["p_X(x)","p_Y(y)","p_X(x)p_Y(y)","p_X(x)/p_Y(y)"]'::jsonb,
  'Observing Y=y gives no information about X, so its PMF does not change.'
),
(
  'probability-chapter-2',
  'C2-58',
  91,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'If X and Y are independent, which expectation identity is guaranteed?',
  'E[XY]=E[X]E[Y]',
  '["E[XY]=E[X]+E[Y]","E[X/Y]=E[X]/E[Y] in every case","E[X]=E[Y]","E[XY]=E[X]E[Y]"]'::jsonb,
  'Factorization of the joint PMF lets the double sum split into a product of expectations.'
),
(
  'probability-chapter-2',
  'C2-59',
  92,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'If X and Y are independent, what can be said about g(X) and h(Y)?',
  'They are independent',
  '["They always have the same PMF","They must have zero variance","They are independent","They are always equal"]'::jsonb,
  'Applying separate functions does not introduce interaction between independent variables.'
),
(
  'probability-chapter-2',
  'C2-60',
  91,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'Which statement about conditional and unconditional independence is correct?',
  'Neither one implies the other in general',
  '["They are equivalent for every conditioning event","Neither one implies the other in general","Conditional independence always implies independence","Independence always implies conditional independence"]'::jsonb,
  'Conditioning can create or remove dependence, so each property must be checked in its own probability model.'
),
(
  'probability-chapter-2',
  'C2-61',
  93,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'For any jointly distributed X and Y, which identity always holds?',
  'E[X+Y]=E[X]+E[Y]',
  '["E[X+Y]=E[X]+E[Y]","var(X+Y)=var(X)+var(Y)","E[XY]=E[X]E[Y]","p_{X,Y}(x,y)=p_X(x)p_Y(y)"]'::jsonb,
  'Means add without an independence assumption; the other identities generally require independence.'
),
(
  'probability-chapter-2',
  'C2-62',
  93,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'If X and Y are independent with variances 3 and 5, what is var(X+Y)?',
  '8',
  '["15","2","64","8"]'::jsonb,
  'For independent variables, the variance of a sum is the sum of variances: 3+5=8.'
),
(
  'probability-chapter-2',
  'C2-63',
  94,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'X counts successes in n independent Bernoulli(p) trials. What is var(X)?',
  'np(1−p)',
  '["p(1−p)/n","n²p²","np(1−p)","np"]'::jsonb,
  'Write X as a sum of n independent Bernoulli variables and add their variances.'
),
(
  'probability-chapter-2',
  'C2-64',
  95,
  'section_3',
  'step_8',
  'Independence, sums, and estimation',
  'X_1,…,X_n are independent with common mean μ and variance σ². For S_n=(X_1+⋯+X_n)/n, which pair is correct?',
  'E[S_n]=μ and var(S_n)=σ²/n',
  '["E[S_n]=μ and var(S_n)=σ²","E[S_n]=μ and var(S_n)=σ²/n","E[S_n]=nμ and var(S_n)=nσ²","E[S_n]=μ/n and var(S_n)=σ²"]'::jsonb,
  'Averaging preserves the common mean while shrinking the variance by a factor of n.'
)
ON CONFLICT (deck_id, source_id) DO UPDATE SET
  source_page = EXCLUDED.source_page,
  section = EXCLUDED.section,
  step = EXCLUDED.step,
  step_title = EXCLUDED.step_title,
  japanese_word = EXCLUDED.japanese_word,
  english = EXCLUDED.english,
  authored_options = EXCLUDED.authored_options,
  explanation = EXCLUDED.explanation;
