-- Compatibility tables for the unmodified original app, in the separate quizz
-- project. Only vocabulary is public; no account or progress access is changed.
create table public.words10k (
 id bigint generated by default as identity primary key,
 japanese_word text not null, english text not null,
 japanese_reading text, word_audio_path text, english_audio_path text,
 example_sentence_japanese text, example_sentence_reading text,
 example_sentence_english text, sentence_audio_path text,
 section text not null, step text not null,
 frequency_rank integer, source_frequency_rank integer, source_frequency bigint
);
create index words10k_section_step_idx on public.words10k(section,step,id);
alter table public.words10k enable row level security;
revoke all on public.words10k from anon,authenticated;
grant all on public.words10k to service_role;
grant usage,select on sequence public.words10k_id_seq to service_role;
grant select on public.words10k to anon,authenticated;
create policy vocabulary_read on public.words10k for select to anon,authenticated using (true);
