INSERT INTO public.learning_decks (
  id, title, description, question_label, answer_label, question_format
) VALUES (
  'probability-chapter-1',
  'Probability · Sample Space and Probability',
  '102 questions following Chapter 1 of Bertsekas and Tsitsiklis. Start with Notation, then learn sets, probability models, conditioning, Bayes, independence and counting.',
  'Question',
  'Answer',
  'multiple_choice'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  question_label = EXCLUDED.question_label,
  answer_label = EXCLUDED.answer_label,
  question_format = EXCLUDED.question_format;

INSERT INTO public.words10k (
  deck_id,
  source_id,
  source_page,
  section,
  step,
  step_title,
  japanese_word,
  english,
  authored_options,
  explanation
) VALUES
(
  'probability-chapter-1',
  'N-01',
  11,
  'section_2',
  'step_1',
  'Notation',
  'What does Ω denote in a probability model?',
  'The sample space',
  '["The sample space","The probability law","The empty event","The number of outcomes"]'::jsonb,
  'Ω is the set of all possible outcomes; it is the universal set for the model.'
),
(
  'probability-chapter-1',
  'N-02',
  8,
  'section_2',
  'step_1',
  'Notation',
  'What does ∅ denote?',
  'The empty set',
  '["The empty set","A set containing the number 0","An unknown probability","The entire sample space"]'::jsonb,
  '∅ has no elements. The book also prints the empty-set symbol as Ø.'
),
(
  'probability-chapter-1',
  'N-03',
  8,
  'section_2',
  'step_1',
  'Notation',
  'What do the braces in {1, 2, 3} indicate?',
  'A set containing 1, 2 and 3',
  '["A set containing 1, 2 and 3","The sum 1 + 2 + 3","An ordered sequence that must occur in that order","Every real number between 1 and 3"]'::jsonb,
  'Braces list set elements; their order does not matter.'
),
(
  'probability-chapter-1',
  'N-04',
  8,
  'section_2',
  'step_1',
  'Notation',
  'What does x ∈ A mean?',
  'x is an element of A',
  '["x is outside A","x is a subset of A","x equals the probability of A","x is an element of A"]'::jsonb,
  '∈ expresses membership of an element in a set.'
),
(
  'probability-chapter-1',
  'N-05',
  8,
  'section_2',
  'step_1',
  'Notation',
  'What does x ∉ A mean?',
  'x is not an element of A',
  '["A is empty","x is a subset of A","A has probability zero","x is not an element of A"]'::jsonb,
  '∉ negates membership; it says nothing about whether A is empty.'
),
(
  'probability-chapter-1',
  'N-06',
  9,
  'section_2',
  'step_1',
  'Notation',
  'In this book, what does A ⊂ B mean?',
  'Every element of A is also in B; equality is allowed',
  '["A and B have no common elements","Every element of A is also in B; equality is allowed","A and B must be different sets","A is one element of B"]'::jsonb,
  'This edition uses ⊂ for inclusive containment. Modern texts often use ⊆ for this meaning and reserve ⊂ for strict containment.'
),
(
  'probability-chapter-1',
  'N-07',
  9,
  'section_2',
  'step_1',
  'Notation',
  'In this book, what does B ⊃ A mean?',
  'B contains every element of A',
  '["B has strictly more elements than A","B contains every element of A","B contains no element of A","B belongs to A as one element"]'::jsonb,
  'It is the reverse way to write A ⊂ B; the book allows equality.'
),
(
  'probability-chapter-1',
  'N-08',
  9,
  'section_2',
  'step_1',
  'Notation',
  'What does A ∪ B mean?',
  'Outcomes in A or B, including those in both',
  '["Only outcomes in both A and B","Outcomes in A or B, including those in both","Outcomes in neither A nor B","Outcomes in exactly one of A and B"]'::jsonb,
  'Union uses inclusive “or”: shared outcomes are included.'
),
(
  'probability-chapter-1',
  'N-09',
  9,
  'section_2',
  'step_1',
  'Notation',
  'What does A ∩ B mean?',
  'Outcomes in both A and B',
  '["Outcomes in at least one of A and B","Outcomes in both A and B","Outcomes in A but not B","Outcomes in neither A nor B"]'::jsonb,
  'Intersection corresponds to “and”.'
),
(
  'probability-chapter-1',
  'N-10',
  9,
  'section_2',
  'step_1',
  'Notation',
  'What does Aᶜ denote?',
  'All outcomes in Ω that are not in A',
  '["A raised to the power c","The intersection of A and an event named c","All outcomes in Ω that are not in A","The number of outcomes in A"]'::jsonb,
  'The superscript c denotes complement relative to the chosen universe Ω.'
),
(
  'probability-chapter-1',
  'N-11',
  14,
  'section_2',
  'step_1',
  'Notation',
  'What does P(A) denote?',
  'The probability that event A occurs',
  '["The probability that event A occurs","The probability law’s sample space","The complement of A","The number of elements in A"]'::jsonb,
  'P maps an event to its probability.'
),
(
  'probability-chapter-1',
  'N-12',
  22,
  'section_2',
  'step_1',
  'Notation',
  'How do you read P(A | B)?',
  'The probability of A given B',
  '["The probability of A or B","The probability of A divided by the probability of B","The probability of A given B","The probability of B given A"]'::jsonb,
  'The vertical bar means “given” here. Under the chapter’s ratio definition, P(B) must be positive.'
),
(
  'probability-chapter-1',
  'N-13',
  16,
  'section_2',
  'step_1',
  'Notation',
  'For a finite set A, what does |A| mean in our questions?',
  'The number of elements in A',
  '["The complement of A","The length of every event A","The number of elements in A","The probability of A"]'::jsonb,
  'This is cardinality notation used in the draft. The chapter usually writes “number of elements” in words; geometric length is a different concept.'
),
(
  'probability-chapter-1',
  'N-14',
  9,
  'section_2',
  'step_1',
  'Notation',
  'How do you read the bar in {x | 0 ≤ x ≤ 1}?',
  'Such that',
  '["Given that event x occurred","Or","Such that","Divided by"]'::jsonb,
  'This describes the set of x such that the stated condition holds. It is set-builder notation, not conditional probability.'
),
(
  'probability-chapter-1',
  'N-15',
  9,
  'section_2',
  'step_1',
  'Notation',
  'What does the interval [a, b] contain, assuming a ≤ b?',
  'All real numbers from a to b, including both endpoints',
  '["All real numbers strictly between a and b","Only the integers from a to b","Only a and b","All real numbers from a to b, including both endpoints"]'::jsonb,
  'Square brackets include the endpoints; braces {a, b} instead list just the endpoints.'
),
(
  'probability-chapter-1',
  'N-16',
  10,
  'section_2',
  'step_1',
  'Notation',
  'What does ℝ denote (printed ℜ in this book)?',
  'The set of real numbers',
  '["The set of real numbers","The set of all probability laws","The set of positive integers","A randomly selected event"]'::jsonb,
  'The chapter calls real numbers scalars and uses ℜ for their set.'
),
(
  'probability-chapter-1',
  'N-17',
  10,
  'section_2',
  'step_1',
  'Notation',
  'What does ℝ² denote?',
  'The set of all ordered pairs of real numbers',
  '["The probability of two independent events","The set of all ordered pairs of real numbers","A set containing exactly two numbers","The set of squares of real numbers"]'::jsonb,
  'ℝ² is the real plane. Similarly, ℝ³ consists of triples and describes three-dimensional space.'
),
(
  'probability-chapter-1',
  'N-18',
  10,
  'section_2',
  'step_1',
  'Notation',
  'In an outcome written as the ordered pair (x, y), does order matter?',
  'Yes: the first and second positions have different roles',
  '["Only if x and y are integers","Only if x and y have equal probability","No: it means the same set as {x, y}","Yes: the first and second positions have different roles"]'::jsonb,
  'For two rolls, the first coordinate can record the first roll and the second the second roll.'
),
(
  'probability-chapter-1',
  'N-19',
  18,
  'section_2',
  'step_1',
  'Notation',
  'What does [0, 1] × [0, 1] denote?',
  'All pairs (x, y) with both coordinates in [0, 1]',
  '["Two independent events, by notation alone","All pairs (x, y) with both coordinates in [0, 1]","Only numbers obtained by multiplying the endpoints","Only the diagonal pairs with x = y"]'::jsonb,
  'This is a Cartesian product: the unit square. The symbol does not itself impose a probability law or independence.'
),
(
  'probability-chapter-1',
  'N-20',
  27,
  'section_2',
  'step_1',
  'Notation',
  'In a collection A₁, A₂, …, Aₙ, what does the subscript i in Aᵢ indicate?',
  'Which event in the collection is meant',
  '["The complement of A","A raised to the power i","Which event in the collection is meant","The probability of A multiplied by i"]'::jsonb,
  'A subscript labels an indexed event; it is not an exponent.'
),
(
  'probability-chapter-1',
  'N-21',
  9,
  'section_2',
  'step_1',
  'Notation',
  'What does ⋃ᵢ₌₁ⁿ Aᵢ mean?',
  'The union of A₁ through Aₙ',
  '["The intersection of A₁ through Aₙ","The set containing only the event Aₙ","The sum of the probabilities of A₁ through Aₙ","The union of A₁ through Aₙ"]'::jsonb,
  'An outcome belongs to this union if it belongs to at least one indexed event.'
),
(
  'probability-chapter-1',
  'N-22',
  9,
  'section_2',
  'step_1',
  'Notation',
  'What does ⋂ᵢ₌₁ⁿ Aᵢ mean?',
  'The intersection of A₁ through Aₙ',
  '["The product of their probabilities","The complement of Aₙ","The union of A₁ through Aₙ","The intersection of A₁ through Aₙ"]'::jsonb,
  'An outcome belongs to this intersection if it belongs to every indexed event.'
),
(
  'probability-chapter-1',
  'N-23',
  19,
  'section_2',
  'step_1',
  'Notation',
  'What does Σᵢ₌₁³ pᵢ mean?',
  'p₁ + p₂ + p₃',
  '["p₁ + p₂ + p₃","p₁ × p₂ × p₃","3 × p₁ in every case","p₃ alone"]'::jsonb,
  'The lower and upper limits specify the included indices; Σ means add the terms.'
),
(
  'probability-chapter-1',
  'N-24',
  41,
  'section_2',
  'step_1',
  'Notation',
  'What does ∏ᵢ₌₁³ pᵢ mean?',
  'p₁ × p₂ × p₃',
  '["p₁ × p₂ × p₃","The union of three events","p₁ + p₂ + p₃","p₁ raised to p₃"]'::jsonb,
  '∏ means multiply the indexed terms. Multiplication of numbers is distinct from intersection of events.'
),
(
  'probability-chapter-1',
  'N-25',
  9,
  'section_2',
  'step_1',
  'Notation',
  'In ⋃ᵢ₌₁^∞ Aᵢ, what does the upper limit ∞ tell you?',
  'Include every positive-integer index, without a finite last index',
  '["The union has probability greater than 1","There is one final event called A∞","Include every positive-integer index, without a finite last index","The events are indexed by every real number"]'::jsonb,
  'The notation specifies a countably infinite collection A₁, A₂, … . It does not specify its probability.'
),
(
  'probability-chapter-1',
  'N-26',
  8,
  'section_2',
  'step_1',
  'Notation',
  'What do the dots mean in {1, 2, 3, …}?',
  'The displayed pattern continues',
  '["One element has been lost","The set contains every real number","The displayed pattern continues","The set stops at 3"]'::jsonb,
  'An ellipsis abbreviates the continuing pattern; here it lists the positive integers.'
),
(
  'probability-chapter-1',
  'N-27',
  45,
  'section_2',
  'step_1',
  'Notation',
  'For a positive integer n, what does n! mean?',
  'The product 1 × 2 × … × n',
  '["The sum 1 + 2 + … + n","n divided by n − 1","n multiplied by itself n times","The product 1 × 2 × … × n"]'::jsonb,
  'The exclamation mark denotes factorial.'
),
(
  'probability-chapter-1',
  'N-28',
  46,
  'section_2',
  'step_1',
  'Notation',
  'What is 0! ?',
  '1',
  '["Undefined","Infinity","1","0"]'::jsonb,
  'The convention 0! = 1 makes the counting formulas apply at boundary cases.'
),
(
  'probability-chapter-1',
  'N-29',
  50,
  'section_2',
  'step_1',
  'Notation',
  'The book places k below n inside parentheses, read “n choose k”. What does this count?',
  'Unordered selections of k distinct objects from n distinct objects',
  '["Unordered selections of k distinct objects from n distinct objects","All subsets of an n-element set, regardless of size","Selections of k objects allowing repeated choices","Ordered selections of k distinct objects from n distinct objects"]'::jsonb,
  'The draft writes the same binomial coefficient as C(n, k). It equals n!/[k!(n − k)!] for 0 ≤ k ≤ n.'
),
(
  'probability-chapter-1',
  'N-30',
  51,
  'section_2',
  'step_1',
  'Notation',
  'The book places n above n₁, …, nᵣ inside parentheses. What does this coefficient count?',
  'Ways to assign n distinct objects to labeled groups of sizes n₁, …, nᵣ',
  '["Only the ways to choose the first group","Partitions where every ordering inside each group counts separately","All ordered arrangements of n objects without grouping","Ways to assign n distinct objects to labeled groups of sizes n₁, …, nᵣ"]'::jsonb,
  'With nonnegative group sizes summing to n, the multinomial coefficient is n!/(n₁!…nᵣ!). Group labels matter; order within a group does not.'
),
(
  'probability-chapter-1',
  'N-31',
  19,
  'section_2',
  'step_1',
  'Notation',
  'For real numbers x and y, what does |x − y| mean?',
  'The nonnegative distance between x and y',
  '["The difference x − y, even when negative","The nonnegative distance between x and y","The probability of x given y","The number of elements in a set named x − y"]'::jsonb,
  'Bars around a number indicate absolute value. This differs from bars around a finite set, which denote cardinality in the draft.'
),
(
  'probability-chapter-1',
  'N-32',
  9,
  'section_2',
  'step_1',
  'Notation',
  'What does 0 ≤ x ≤ 1 mean?',
  'x is between 0 and 1, including the endpoints',
  '["x must equal 0 or 1","x is between 0 and 1, including the endpoints","x is strictly between 0 and 1","x must be an integer"]'::jsonb,
  '≤ means less than or equal to; ≥ means greater than or equal to. The signs < and > exclude equality.'
),
(
  'probability-chapter-1',
  'N-33',
  38,
  'section_2',
  'step_1',
  'Notation',
  'What does P(A ∩ B) ≠ P(A)P(B) assert?',
  'The two quantities are not equal',
  '["The quantities are approximately equal","The two quantities are not equal","One of the probabilities is undefined","The left side is always larger"]'::jsonb,
  '≠ states inequality without specifying which side is larger.'
),
(
  'probability-chapter-1',
  'N-34',
  36,
  'section_2',
  'step_1',
  'Notation',
  'What does the symbol ≈ mean in a calculated probability?',
  'Approximately equal to',
  '["Approximately equal to","Exactly equal to","Not equal to","Less than or equal to"]'::jsonb,
  'The book uses ≈ when reporting rounded numerical results.'
),
(
  'probability-chapter-1',
  'N-35',
  44,
  'section_2',
  'step_1',
  'Notation',
  'For positive integer k, what does pᵏ mean?',
  'p multiplied by itself k times',
  '["p multiplied by itself k times","p divided by k","The kth member of a collection p₁, p₂, …","p multiplied by k"]'::jsonb,
  'A superscript k is an exponent here; a subscript k would instead label a term.'
),
(
  'probability-chapter-1',
  'N-36',
  24,
  'section_2',
  'step_1',
  'Notation',
  'If X = 2 and Y = 4, what are min(X, Y) and max(X, Y)?',
  '2 and 4, respectively',
  '["4 and 2, respectively","2 and 4, respectively","3 and 3, respectively","6 and 8, respectively"]'::jsonb,
  'min selects the smaller value and max the larger. These operators appear in the chapter’s dice examples.'
),
(
  'probability-chapter-1',
  'N-37',
  45,
  'section_2',
  'step_1',
  'Notation',
  'In the chapter’s n-toss model, p is the probability of heads on one toss. What does p(k) denote?',
  'The probability of exactly k heads in all n tosses',
  '["p multiplied by k","The probability of exactly k heads in all n tosses","The probability of a particular sequence with k heads","The probability of the kth toss being heads"]'::jsonb,
  'Parentheses indicate a function evaluated at k. Here the chapter defines p(k) as a binomial probability, which counts all qualifying sequences.'
),
(
  'probability-chapter-1',
  'N-38',
  18,
  'section_2',
  'step_1',
  'Notation',
  'In the chapter’s footnote on continuous models, what does ∫ₛ dt represent for a suitable set S ⊆ [0, 1]?',
  'The length of S',
  '["The probability of each individual point in S","The number of individual points in S","The largest point of S","The length of S"]'::jsonb,
  'It integrates the constant 1 over S. In that specific uniform model, this length is P(S). This is recognition only; integration techniques are not required for this deck.'
),
(
  'probability-chapter-1',
  'P1-01',
  11,
  'section_2',
  'step_2',
  'Sets and events',
  'What is a sample space?',
  'The set of all possible outcomes',
  '["The set of equally likely outcomes","Only outcomes with positive probability","The set of all possible outcomes","The set of outcomes already observed"]'::jsonb,
  'A sample space lists what can happen. Equal likelihood is an extra assumption.'
),
(
  'probability-chapter-1',
  'P1-02',
  12,
  'section_2',
  'step_2',
  'Sets and events',
  'What is an event?',
  'A subset of the sample space',
  '["The number of times an experiment is repeated","A probability between 0 and 1","A subset of the sample space","Always exactly one outcome"]'::jsonb,
  'An event is a collection of outcomes; its probability is a separate quantity.'
),
(
  'probability-chapter-1',
  'P1-03',
  9,
  'section_2',
  'step_2',
  'Sets and events',
  'A = {1, 2} and B = {2, 3}. What is A ∪ B?',
  '{1, 2, 3}',
  '["{1, 2, 3}","{1, 2}","{1, 3}","{2}"]'::jsonb,
  'Union includes outcomes in either set, counting shared elements only once.'
),
(
  'probability-chapter-1',
  'P1-04',
  9,
  'section_2',
  'step_2',
  'Sets and events',
  'A = {1, 2} and B = {2, 3}. What is A ∩ B?',
  '{2}',
  '["{1, 2, 3}","{1, 3}","{2}","∅"]'::jsonb,
  'Intersection keeps only the outcomes shared by both sets.'
),
(
  'probability-chapter-1',
  'P1-05',
  9,
  'section_2',
  'step_2',
  'Sets and events',
  'Ω = {1, 2, 3, 4} and A = {1, 4}. What is Aᶜ?',
  '{2, 3}',
  '["{2, 3}","∅","{1, 2, 3, 4}","{1, 4}"]'::jsonb,
  'The complement contains the outcomes in Ω that are not in A.'
),
(
  'probability-chapter-1',
  'P1-06',
  9,
  'section_2',
  'step_2',
  'Sets and events',
  'When are A and B disjoint?',
  'When A ∩ B = ∅',
  '["When A ∩ B = ∅","When P(A) = P(B)","When A ∪ B = Ω","When neither event is a subset of the other"]'::jsonb,
  'Disjoint events have no outcomes in common.'
),
(
  'probability-chapter-1',
  'P1-07',
  9,
  'section_2',
  'step_2',
  'Sets and events',
  'Which collection partitions Ω = {1, 2, 3, 4}?',
  '{1, 2} and {3, 4}',
  '["{1, 2} and {2, 3, 4}","{1, 2, 3, 4} and {4}","{1, 2} and {3, 4}","{1} and {2, 3}"]'::jsonb,
  'A partition covers all of Ω with nonoverlapping sets.'
),
(
  'probability-chapter-1',
  'P1-08',
  10,
  'section_2',
  'step_2',
  'Sets and events',
  'Which expression equals (A ∪ B)ᶜ?',
  'Aᶜ ∩ Bᶜ',
  '["A ∪ B","Aᶜ ∩ Bᶜ","A ∩ B","Aᶜ ∪ Bᶜ"]'::jsonb,
  'Not being in either event means being outside both: de Morgan’s law.'
),
(
  'probability-chapter-1',
  'P1-09',
  11,
  'section_2',
  'step_3',
  'Building a probability model',
  'What two ingredients specify a probabilistic model?',
  'A sample space and a probability law',
  '["A sample space and a probability law","A list of events and their observed counts","A mean and a variance","A sample space and equal probabilities for all outcomes"]'::jsonb,
  'The sample space describes outcomes; the probability law assigns event probabilities.'
),
(
  'probability-chapter-1',
  'P1-10',
  12,
  'section_2',
  'step_3',
  'Building a probability model',
  'What must the outcomes in a sample space be?',
  'Mutually exclusive and collectively exhaustive',
  '["Independent and equally likely","Equally likely and finite","Distinct but not necessarily exhaustive","Mutually exclusive and collectively exhaustive"]'::jsonb,
  'Exactly one listed outcome must occur whenever the experiment is performed.'
),
(
  'probability-chapter-1',
  'P1-11',
  13,
  'section_2',
  'step_3',
  'Building a probability model',
  'You toss a coin three times and want to know whether the first toss is heads. Is recording only the total number of heads sufficient?',
  'No: the order is lost',
  '["Yes, if the coin is fair","No: the order is lost","No: a coin-toss sample space must be infinite","Yes: the total determines the first toss"]'::jsonb,
  'For example, HTT and THT have the same number of heads but different first tosses.'
),
(
  'probability-chapter-1',
  'P1-12',
  9,
  'section_2',
  'step_3',
  'Building a probability model',
  'Which sample space is countably infinite?',
  '{1, 2, 3, …}',
  '["{1, 2, 3, …}","The points inside a unit square","The real interval [0, 1]","{heads, tails}"]'::jsonb,
  'The positive integers can be listed one by one. The real interval cannot; the coin space is finite.'
),
(
  'probability-chapter-1',
  'P1-13',
  14,
  'section_2',
  'step_3',
  'Building a probability model',
  'Which proposed outcome probabilities violate nonnegativity?',
  '−0.1, 0.5, 0.6',
  '["0.2, 0.3, 0.5","0, 0, 1","−0.1, 0.5, 0.6","0, 0.4, 0.6"]'::jsonb,
  'A negative probability is invalid even when the numbers sum to 1.'
),
(
  'probability-chapter-1',
  'P1-14',
  14,
  'section_2',
  'step_3',
  'Building a probability model',
  'What is P(Ω)?',
  '1',
  '["1 divided by the number of outcomes","1","0","The number of outcomes"]'::jsonb,
  'Normalization assigns probability 1 to the entire sample space.'
),
(
  'probability-chapter-1',
  'P1-15',
  14,
  'section_2',
  'step_3',
  'Building a probability model',
  'A and B are disjoint, with P(A) = 0.2 and P(B) = 0.3. What is P(A ∪ B)?',
  '0.5',
  '["0.06","0.3","0.5","0.1"]'::jsonb,
  'Additivity lets us add the probabilities of disjoint events.'
),
(
  'probability-chapter-1',
  'P1-16',
  14,
  'section_2',
  'step_3',
  'Building a probability model',
  'For a countably infinite sequence of disjoint events A₁, A₂, …, what is P(∪ᵢ Aᵢ)?',
  'Σᵢ P(Aᵢ)',
  '["∏ᵢ P(Aᵢ)","Σᵢ P(Aᵢ)","Always 1","The largest individual P(Aᵢ)"]'::jsonb,
  'Countable additivity extends the disjoint-union rule to countably many events; their union need not be all of Ω.'
),
(
  'probability-chapter-1',
  'P1-17',
  16,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'When does P(A) = |A| / |Ω| apply?',
  'When Ω is finite and all its outcomes are equally likely',
  '["Whenever Ω is finite","When Ω is finite and all its outcomes are equally likely","Whenever A and Aᶜ are disjoint","Whenever A contains more than one outcome"]'::jsonb,
  'Counting outcomes is sufficient only under the discrete uniform law.'
),
(
  'probability-chapter-1',
  'P1-18',
  14,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'If P(A) = 0.35, what is P(Aᶜ)?',
  '0.65',
  '["0.35","0.1225","0.65","1.35"]'::jsonb,
  'A and its complement partition Ω, so their probabilities sum to 1.'
),
(
  'probability-chapter-1',
  'P1-19',
  18,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'P(A) = 0.6, P(B) = 0.5 and P(A ∩ B) = 0.2. What is P(A ∪ B)?',
  '0.9',
  '["0.7","0.3","0.9","1.1"]'::jsonb,
  'Add 0.6 and 0.5, then subtract the overlap 0.2 that was counted twice.'
),
(
  'probability-chapter-1',
  'P1-20',
  19,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'Given only P(A) = 0.2 and P(B) = 0.3, what is the smallest guaranteed upper bound for P(A ∪ B)?',
  '0.5',
  '["0.06","1","0.3","0.5"]'::jsonb,
  'The union bound gives at most 0.2 + 0.3. Disjoint events attain this bound.'
),
(
  'probability-chapter-1',
  'P1-21',
  16,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'Ω = {a, b, c}, with probabilities 0.1, 0.3 and 0.6. What is P({a, c})?',
  '0.7',
  '["2/3","0.6","0.06","0.7"]'::jsonb,
  'Add the probabilities of a and c; these outcomes are not equally likely.'
),
(
  'probability-chapter-1',
  'P1-22',
  18,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'A point is chosen uniformly from [0, 1]. What is the probability that it lies in [0.2, 0.5]?',
  '0.3',
  '["0.3","0.15","0.5","0.7"]'::jsonb,
  'For this uniform model, interval probability equals its length: 0.5 − 0.2.'
),
(
  'probability-chapter-1',
  'P1-23',
  18,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'A point is chosen uniformly from [0, 1]. What is the probability of choosing exactly 0.5?',
  '0',
  '["0","1","It cannot be assigned in this model","0.5"]'::jsonb,
  'A single point has zero length. In a continuous model, probability zero does not necessarily mean an empty event.'
),
(
  'probability-chapter-1',
  'P1-24',
  18,
  'section_2',
  'step_4',
  'Calculating event probabilities',
  'A point (x, y) is chosen uniformly from the unit square. What is P(x + y ≤ 1)?',
  '1/2',
  '["1/2","1/4","3/4","1"]'::jsonb,
  'The diagonal divides the square into two equal-area triangles; the event occupies one of them.'
),
(
  'probability-chapter-1',
  'P1-25',
  22,
  'section_2',
  'step_5',
  'Conditional probability',
  'For P(B) > 0, which formula defines P(A | B)?',
  'P(A ∩ B) / P(B)',
  '["P(A) / P(B)","P(A ∪ B) / P(B)","P(A ∩ B) / P(A)","P(A ∩ B) / P(B)"]'::jsonb,
  'Conditioning retains the probability mass in B and renormalizes it to 1.'
),
(
  'probability-chapter-1',
  'P1-26',
  22,
  'section_2',
  'step_5',
  'Conditional probability',
  'If P(B) = 0, what does the chapter’s ratio definition say about P(A | B)?',
  'It is undefined',
  '["It is undefined","It is P(A)","It is 0","It is 1"]'::jsonb,
  'The ratio would divide by zero. More advanced forms of conditioning are outside this chapter.'
),
(
  'probability-chapter-1',
  'P1-27',
  22,
  'section_2',
  'step_5',
  'Conditional probability',
  'A fair six-sided die shows an even number. What is the probability it shows 6?',
  '1/3',
  '["1/3","1/2","2/3","1/6"]'::jsonb,
  'Only 2, 4 and 6 remain possible, and they are equally likely.'
),
(
  'probability-chapter-1',
  'P1-28',
  24,
  'section_2',
  'step_5',
  'Conditional probability',
  'Two independent fair coins are tossed. Given at least one head, what is the probability of two heads?',
  '1/3',
  '["2/3","1/2","1/4","1/3"]'::jsonb,
  'The remaining equally likely outcomes are HH, HT and TH; only HH has two heads.'
),
(
  'probability-chapter-1',
  'P1-29',
  28,
  'section_2',
  'step_5',
  'Conditional probability',
  'A bag contains 3 red and 2 blue balls. Two balls are drawn uniformly without replacement. What is the probability both are red?',
  '3/10',
  '["3/5","3/10","1/5","9/25"]'::jsonb,
  'Multiply 3/5 for the first red by 2/4 for the second red after the first is removed.'
),
(
  'probability-chapter-1',
  'P1-30',
  26,
  'section_2',
  'step_5',
  'Conditional probability',
  'A tree branch has probability 0.4. A following branch has conditional probability 0.3 given the first. What is the probability of the full path?',
  '0.12',
  '["0.12","0.7","0.1","0.3"]'::jsonb,
  'Multiply the probabilities along the path: 0.4 × 0.3.'
),
(
  'probability-chapter-1',
  'P1-31',
  27,
  'section_2',
  'step_5',
  'Conditional probability',
  'When all conditioning events have positive probability, which formula always gives P(A ∩ B ∩ C)?',
  'P(A)P(B | A)P(C | A ∩ B)',
  '["P(A)P(B | A)P(C | B)","P(A)P(B)P(C)","P(A)P(B | A)P(C | A ∩ B)","P(A) + P(B | A) + P(C | B)"]'::jsonb,
  'The chain rule conditions each stage on the entire preceding path; independence is not required.'
),
(
  'probability-chapter-1',
  'P1-32',
  23,
  'section_2',
  'step_5',
  'Conditional probability',
  'If P(A | B) = 0.7 and P(B) > 0, what is P(Aᶜ | B)?',
  '0.3',
  '["Cannot be determined","1","0.7","0.3"]'::jsonb,
  'A conditional probability law also obeys the complement rule.'
),
(
  'probability-chapter-1',
  'P1-33',
  31,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'A₁ and A₂ partition Ω and both have positive probability. Which expression gives P(B)?',
  'P(A₁)P(B | A₁) + P(A₂)P(B | A₂)',
  '["P(A₁ | B) + P(A₂ | B)","P(A₁)P(B | A₁) + P(A₂)P(B | A₂)","P(A₁)P(A₂)P(B)","P(B | A₁) + P(B | A₂)"]'::jsonb,
  'Weight each conditional probability by the probability of its scenario.'
),
(
  'probability-chapter-1',
  'P1-34',
  31,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'You face a beginner with probability 0.75 and an expert otherwise. Your win probabilities are 0.8 and 0.2 respectively. What is your overall win probability?',
  '0.65',
  '["0.5","0.8","0.65","0.6"]'::jsonb,
  'Use total probability: 0.75 × 0.8 + 0.25 × 0.2 = 0.65.'
),
(
  'probability-chapter-1',
  'P1-35',
  31,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'Machine A makes 60% of items and defects occur in 2% of its output. Machine B makes the rest with a 5% defect rate. What fraction of all items are defective?',
  '3.2%',
  '["2%","3.5%","3.2%","7%"]'::jsonb,
  'The weighted defect rate is 0.6 × 0.02 + 0.4 × 0.05 = 0.032.'
),
(
  'probability-chapter-1',
  'P1-36',
  34,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'Machine A makes 60% of items with a 2% defect rate; B makes 40% with a 5% defect rate. Given a defective item, what is the probability it came from B?',
  '5/8',
  '["1/20","2/5","3/8","5/8"]'::jsonb,
  'B contributes 0.4 × 0.05 = 0.02; all defects have probability 0.032. The ratio is 0.02/0.032 = 5/8.'
),
(
  'probability-chapter-1',
  'P1-37',
  34,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'Does P(A | B) generally equal P(B | A)?',
  'No: they condition on different events',
  '["No: they condition on different events","Only when A and B are disjoint","Yes: intersection is symmetric","Yes, whenever both probabilities are defined"]'::jsonb,
  'The numerators agree, but the denominators P(B) and P(A) can differ.'
),
(
  'probability-chapter-1',
  'P1-38',
  35,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'A faulty device is selected with probability 0.01. An alarm sounds with probability 0.9 for faulty devices and 0.1 for working devices. Given an alarm, what is the probability the device is faulty?',
  '1/12',
  '["1/100","1/12","1/10","9/10"]'::jsonb,
  'Fault-and-alarm probability is 0.009; total alarm probability is 0.009 + 0.099 = 0.108. Their ratio is 1/12.'
),
(
  'probability-chapter-1',
  'P1-39',
  34,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'Assume P(A) > 0 and P(B) > 0. Which expression gives P(A | B) using Bayes’ rule?',
  'P(B | A)P(A) / P(B)',
  '["P(B | A)P(A) / P(B)","P(A)P(B) / P(B | A)","P(B | A)P(B) / P(A)","P(B | A) / P(A)"]'::jsonb,
  'Bayes’ rule reverses the conditioning using the prior P(A) and the evidence probability P(B).'
),
(
  'probability-chapter-1',
  'P1-40',
  35,
  'section_2',
  'step_6',
  'Total probability and Bayes’ rule',
  'You know how common each cause is and how often each cause produces an observed signal. Which rule updates the probabilities of the causes after seeing the signal?',
  'Bayes’ rule',
  '["The permutation formula","The counting principle","The disjoint-addition rule alone","Bayes’ rule"]'::jsonb,
  'The task is to infer a cause from evidence, which reverses the known conditional probabilities.'
),
(
  'probability-chapter-1',
  'P1-41',
  37,
  'section_2',
  'step_7',
  'Independence',
  'Which equality defines independence of A and B?',
  'P(A ∩ B) = P(A)P(B)',
  '["P(A ∪ B) = P(A) + P(B)","P(A ∩ B) = 0","P(A) = P(B)","P(A ∩ B) = P(A)P(B)"]'::jsonb,
  'Independence is a factorization of the intersection probability, not a statement about overlap or equal probabilities.'
),
(
  'probability-chapter-1',
  'P1-42',
  37,
  'section_2',
  'step_7',
  'Independence',
  'P(A) = 0.4, P(B) = 0.5 and P(A ∩ B) = 0.2. Are A and B independent?',
  'Yes, since 0.2 = 0.4 × 0.5',
  '["No, since their probabilities differ","Cannot be decided without knowing P(A ∪ B)","Yes, since 0.2 = 0.4 × 0.5","No, since the events overlap"]'::jsonb,
  'The product criterion holds exactly.'
),
(
  'probability-chapter-1',
  'P1-43',
  37,
  'section_2',
  'step_7',
  'Independence',
  'A and B are disjoint and both have positive probability. Can they be independent?',
  'No',
  '["Only if P(A) + P(B) = 1","No","Yes, always","Only if P(A) = P(B)"]'::jsonb,
  'Their intersection has probability 0, but P(A)P(B) is positive.'
),
(
  'probability-chapter-1',
  'P1-44',
  40,
  'section_2',
  'step_7',
  'Independence',
  'A and B are independent, P(A) = 0.3 and P(B) = 0.4. What is P(A ∩ Bᶜ)?',
  '0.18',
  '["0.7","0.12","0.42","0.18"]'::jsonb,
  'A is also independent of Bᶜ, so the probability is 0.3 × 0.6.'
),
(
  'probability-chapter-1',
  'P1-45',
  38,
  'section_2',
  'step_7',
  'Independence',
  'For P(C) > 0, which equality defines independence of A and B conditional on C?',
  'P(A ∩ B | C) = P(A | C)P(B | C)',
  '["P(A | C) = P(B | C)","P(A ∩ B | C) = P(A)P(B)","P(A ∩ B | C) = P(A | C) + P(B | C)","P(A ∩ B | C) = P(A | C)P(B | C)"]'::jsonb,
  'Conditional independence uses probabilities under the same conditional law.'
),
(
  'probability-chapter-1',
  'P1-46',
  39,
  'section_2',
  'step_7',
  'Independence',
  'How are independence and conditional independence related in general?',
  'Neither implies the other',
  '["Neither implies the other","Independence always implies conditional independence","Conditional independence always implies independence","They are equivalent whenever the conditioning event has positive probability"]'::jsonb,
  'Learning additional information can create or remove dependence; both directions have counterexamples.'
),
(
  'probability-chapter-1',
  'P1-47',
  41,
  'section_2',
  'step_7',
  'Independence',
  'Is pairwise independence of three events enough to guarantee mutual independence?',
  'No',
  '["Only when all three have probability 1/2","Yes","No","Only when their probabilities add to 1"]'::jsonb,
  'Mutual independence also requires the three-event intersection to factor.'
),
(
  'probability-chapter-1',
  'P1-48',
  41,
  'section_2',
  'step_7',
  'Independence',
  'Two independent fair coins are tossed. Let A = first toss is heads, B = second toss is heads, and C = tosses differ. Are A, B and C mutually independent?',
  'No: the triple intersection has probability 0, not 1/8',
  '["Yes: every pair is independent","No: mutual independence requires the events to be disjoint","No: the triple intersection has probability 0, not 1/8","Yes: each event has probability 1/2"]'::jsonb,
  'Each event has probability 1/2, but A ∩ B ∩ C is empty. Pairwise independence is insufficient.'
),
(
  'probability-chapter-1',
  'P1-49',
  44,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'What describes a sequence of independent Bernoulli trials?',
  'Independent two-outcome trials with the same success probability',
  '["Any repeated experiment, even if outcomes affect later trials","Independent two-outcome trials with the same success probability","Trials with exactly one success overall","Independent trials that must each have success probability 1/2"]'::jsonb,
  'The chapter considers identical independent stages, each labeled success or failure.'
),
(
  'probability-chapter-1',
  'P1-50',
  44,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'A coin has P(H) = 0.6 on each independent toss. What is the probability of the specific sequence HHT?',
  '0.144',
  '["0.144","0.432","0.216","0.096"]'::jsonb,
  'A specific sequence has probability 0.6 × 0.6 × 0.4. Do not multiply by the number of other sequences.'
),
(
  'probability-chapter-1',
  'P1-51',
  45,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'How many sequences of four coin tosses contain exactly two heads?',
  '6',
  '["16","6","4","8"]'::jsonb,
  'Choose the two head positions: C(4, 2) = 6. The order of heads and tails distinguishes sequences.'
),
(
  'probability-chapter-1',
  'P1-52',
  45,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'For four independent fair coin tosses, what is the probability of exactly two heads?',
  '3/8',
  '["1/4","3/8","1/16","1/2"]'::jsonb,
  'There are 6 qualifying sequences, each with probability 1/16, giving 6/16 = 3/8.'
),
(
  'probability-chapter-1',
  'P1-53',
  44,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'A trial succeeds with probability 0.2. Across three independent trials, what is the probability of at least one success?',
  '0.488',
  '["0.512","0.488","0.6","0.008"]'::jsonb,
  'Subtract the probability of no successes: 1 − 0.8³ = 0.488.'
),
(
  'probability-chapter-1',
  'P1-54',
  46,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'Each of three users independently needs a connection with probability 1/2. A system has two connections. What is the probability demand exceeds capacity?',
  '1/8',
  '["1/8","1/2","7/8","3/8"]'::jsonb,
  'Demand exceeds two only when all three need a connection: (1/2)³.'
),
(
  'probability-chapter-1',
  'P1-55',
  43,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'Two independent components work with probabilities 0.9 and 0.8. A system needs both to work. What is its success probability?',
  '0.72',
  '["0.02","0.85","0.72","0.98"]'::jsonb,
  'For a series system, multiply the component success probabilities.'
),
(
  'probability-chapter-1',
  'P1-56',
  43,
  'section_2',
  'step_8',
  'Independent trials and reliability',
  'Two independent components work with probabilities 0.9 and 0.8. A system needs at least one to work. What is its success probability?',
  '0.98',
  '["0.17","0.02","0.98","0.72"]'::jsonb,
  'A parallel system fails only if both fail: success probability is 1 − 0.1 × 0.2.'
),
(
  'probability-chapter-1',
  'P1-57',
  48,
  'section_2',
  'step_9',
  'Counting',
  'A code has one of 3 letters followed by one of 4 digits. How many codes are possible?',
  '12',
  '["81","12","7","64"]'::jsonb,
  'The choices form two stages: 3 × 4 = 12.'
),
(
  'probability-chapter-1',
  'P1-58',
  48,
  'section_2',
  'step_9',
  'Counting',
  'How many subsets does a set with 5 elements have, including ∅ and the whole set?',
  '32',
  '["10","25","120","32"]'::jsonb,
  'Each of the five elements is either included or excluded, giving 2⁵ subsets.'
),
(
  'probability-chapter-1',
  'P1-59',
  49,
  'section_2',
  'step_9',
  'Counting',
  'In how many orders can 4 distinct books be arranged in a row?',
  '24',
  '["24","12","4","16"]'::jsonb,
  'Arrange all four distinct objects: 4! = 24.'
),
(
  'probability-chapter-1',
  'P1-60',
  49,
  'section_2',
  'step_9',
  'Counting',
  'From 5 people, choose a president and a different secretary. How many assignments are possible?',
  '20',
  '["20","10","25","120"]'::jsonb,
  'The roles are distinct and no person fills both: 5 × 4 = 20.'
),
(
  'probability-chapter-1',
  'P1-61',
  50,
  'section_2',
  'step_9',
  'Counting',
  'How many unordered teams of 2 can be chosen from 5 people?',
  '10',
  '["10","25","20","5"]'::jsonb,
  'Order does not matter: C(5, 2) = 5!/(2!3!) = 10.'
),
(
  'probability-chapter-1',
  'P1-62',
  49,
  'section_2',
  'step_9',
  'Counting',
  'Which formula counts ordered selections of k distinct objects from n distinct objects, without replacement (0 ≤ k ≤ n)?',
  'n! / (n − k)!',
  '["k! / (n − k)!","nᵏ","n! / [k!(n − k)!]","n! / (n − k)!"]'::jsonb,
  'Ordering matters and repetitions are forbidden, so use k-permutations.'
),
(
  'probability-chapter-1',
  'P1-63',
  51,
  'section_2',
  'step_9',
  'Counting',
  'Six distinct people are assigned to labeled groups A, B and C, with 2 people per group. How many assignments are possible?',
  '90',
  '["90","15","216","720"]'::jsonb,
  'Use the multinomial count 6!/(2!2!2!) = 90. The group labels matter; within-group order does not.'
),
(
  'probability-chapter-1',
  'P1-64',
  52,
  'section_2',
  'step_9',
  'Counting',
  'How many distinct letter sequences can be formed by rearranging LEVEL?',
  '30',
  '["10","60","30","120"]'::jsonb,
  'There are five letters, with L repeated twice and E twice: 5!/(2!2!) = 30.'
)
ON CONFLICT (deck_id, source_id) DO UPDATE SET
  source_page = EXCLUDED.source_page,
  section = EXCLUDED.section,
  step = EXCLUDED.step,
  step_title = EXCLUDED.step_title,
  japanese_word = EXCLUDED.japanese_word,
  english = EXCLUDED.english,
  authored_options = EXCLUDED.authored_options,
  explanation = EXCLUDED.explanation;
